export const SUDDEN_DEATH_QUESTIONS = [
  { id: 'sd-01', text: 'What is the capital of Burkina Faso?', answer: 'Ouagadougou' },
  { id: 'sd-02', text: 'Which empire was ruled by Mansa Musa?', answer: 'Mali Empire' },
  { id: 'sd-03', text: 'What strait links the Red Sea to the Gulf of Aden?', answer: 'Bab-el-Mandeb' },
  { id: 'sd-04', text: 'What is the official capital of Ivory Coast?', answer: 'Yamoussoukro' },
  { id: 'sd-05', text: 'What currency is used in Botswana?', answer: 'Pula' },
  { id: 'sd-06', text: 'What is the capital of Equatorial Guinea?', answer: 'Malabo' },
  { id: 'sd-07', text: 'Which city hosted the 1963 founding of the Organization of African Unity?', answer: 'Addis Ababa' },
  { id: 'sd-08', text: 'Which river flows over Victoria Falls?', answer: 'Zambezi' },
  { id: 'sd-09', text: 'What is the capital of Comoros?', answer: 'Moroni' },
  { id: 'sd-10', text: 'Which African country contains the enclave nation of Lesotho?', answer: 'South Africa' },
  { id: 'sd-11', text: 'Which desert runs along Namibia\'s Atlantic coast?', answer: 'Namib Desert' },
  { id: 'sd-12', text: 'What is the smallest African country by land area?', answer: 'Seychelles' },
  { id: 'sd-13', text: 'Who wrote the novel "So Long a Letter"?', answer: 'Mariama Ba' },
  { id: 'sd-14', text: 'What is the capital of Chad?', answer: 'N\'Djamena' },
  { id: 'sd-15', text: 'What mountain range stretches across Morocco, Algeria, and Tunisia?', answer: 'Atlas Mountains' },
  { id: 'sd-16', text: 'What is the official capital of Benin?', answer: 'Porto-Novo' },
  { id: 'sd-17', text: 'Which African country includes the semi-autonomous islands of Zanzibar?', answer: 'Tanzania' },
  { id: 'sd-18', text: 'What is the capital of Mauritania?', answer: 'Nouakchott' },
  { id: 'sd-19', text: 'What is the official language of Angola?', answer: 'Portuguese' },
  { id: 'sd-20', text: 'What is the capital of Eritrea?', answer: 'Asmara' },
]
