export default {
  id: 'african-innovations',
  name: 'African Innovations',
  type: 'custom-buzz',
  intro: 'From tech to medicine to culture — buzz with the African innovations that changed the world.',
  rules: [
    'Host reads the question about an African invention or innovation',
    'Teams buzz in with the answer',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: {
    correctPoints: 3,
    wrongPoints: -1,
    stealEnabled: true,
    correctStealPoints: 2,
    wrongStealPoints: 0,
  },
  questions: [
    {
      id: 'ainno-01',
      promptType: 'text',
      promptText: 'Which South African inventor created the first practical engine in 1858, predating similar developments in Europe?',
      answer: 'Francois de Lesseps (or South African engineers)',
      explanation: 'South Africa has a rich history of engineering innovations, including early internal combustion engine development.',
    },
    {
      id: 'ainno-02',
      promptType: 'text',
      promptText: 'M-Pesa, the mobile money system that revolutionized banking in Africa, originated in which country?',
      answer: 'Kenya',
      explanation: 'M-Pesa, launched in 2007 by Safaricom, became the world\'s most successful mobile money platform and pioneered financial inclusion across the continent.',
    },
    {
      id: 'ainno-03',
      promptType: 'text',
      promptText: 'Which Nigerian entrepreneur created the technology platform that powers most of African fintech today?',
      answer: 'Flutterwave (or African fintech innovators)',
      explanation: 'Nigeria has become a hub for fintech innovation in Africa, with companies revolutionizing digital payments and financial services.',
    },
    {
      id: 'ainno-04',
      promptType: 'text',
      promptText: 'The world\'s first full DNA sequence of an African human genome was published in 2020. Which South African scientist led this breakthrough?',
      answer: 'Himla Soodyall',
      explanation: 'This landmark achievement challenged the assumption that all human genomes studied were primarily European.',
    },
    {
      id: 'ainno-05',
      promptType: 'text',
      promptText: 'Which Ethiopian coffee ceremony tradition inspired modern coffee shop culture across Africa and beyond?',
      answer: 'Ethiopian coffee ceremony (jebena)',
      explanation: 'The traditional Ethiopian coffee ceremony, dating back centuries, is a UNESCO-recognized cultural practice that remains central to African social life.',
    },
    {
      id: 'ainno-06',
      promptType: 'text',
      promptText: 'Mpingo wood from Tanzania is prized for making which traditional African instrument that\'s central to many ceremonies?',
      answer: 'Talking drum (or African drums)',
      explanation: 'Mpingo (African blackwood) is considered the finest wood for making drums and is sought by musicians worldwide.',
    },
    {
      id: 'ainno-07',
      promptType: 'text',
      promptText: 'Which South African medical pioneer performed the world\'s first successful heart transplant in 1967?',
      answer: 'Christiaan Barnard',
      explanation: 'Christiaan Barnard at the University of Cape Town performed the groundbreaking surgery that changed modern medicine.',
    },
    {
      id: 'ainno-08',
      promptType: 'text',
      promptText: 'Ubuntu OS, which powers millions of computers worldwide, was created by which South African entrepreneur?',
      answer: 'Mark Shuttleworth',
      explanation: 'Mark Shuttleworth founded Canonical and created Ubuntu, one of the most popular Linux distributions globally.',
    },
    {
      id: 'ainno-09',
      promptType: 'text',
      promptText: 'Which West African country pioneered the use of drones for medical delivery, delivering blood and medicines to remote villages?',
      answer: 'Rwanda',
      explanation: 'Rwanda became a global leader in medical drone delivery, with Zipline delivering time-sensitive medical products to rural clinics.',
    },
    {
      id: 'ainno-10',
      promptType: 'text',
      promptText: 'The world\'s largest solar power plant in a landlocked country was built in which African nation?',
      answer: 'Burkina Faso',
      explanation: 'The Nzérékoré solar facility in Burkina Faso is part of Africa\'s renewable energy revolution.',
    },
    {
      id: 'ainno-11',
      promptType: 'text',
      promptText: 'Which Nigerian author pioneered the "Afrofuturism" genre that\'s now a global cultural movement?',
      answer: 'Nnedi Okorafor',
      explanation: 'Nnedi Okorafor\'s novels and stories blend African culture with science fiction, creating a new literary genre that\'s influenced global pop culture.',
    },
    {
      id: 'ainno-12',
      promptType: 'text',
      promptText: 'Ghana\'s Ashanti people developed which mathematical system centuries before similar concepts appeared in Europe?',
      answer: 'Fractal geometry (or Ashanti design patterns)',
      explanation: 'Ashanti architectural and artistic designs contain fractal patterns independently discovered centuries before mathematical fractal theory.',
    },
    {
      id: 'ainno-13',
      promptType: 'text',
      promptText: 'Which South African jazz musician was the first African artist to win a Grammy Award in the classical music category?',
      answer: 'Miriam Makeba (or other African jazz pioneers)',
      explanation: 'South African musicians broke international barriers and brought African music to global recognition.',
    },
    {
      id: 'ainno-14',
      promptType: 'text',
      promptText: 'The concept of "Ubuntu" — a South African philosophy meaning "I am because we are" — influenced which international movements?',
      answer: 'Peace, ubuntu philosophy, restorative justice',
      explanation: 'Ubuntu philosophy has inspired global movements toward community-based justice and interconnectedness.',
    },
    {
      id: 'ainno-15',
      promptType: 'text',
      promptText: 'Which African country was the first to implement a nationwide digital currency backed by blockchain technology?',
      answer: 'Senegal (or El Salvador/African innovations)',
      explanation: 'Multiple African countries have pioneered blockchain and crypto innovations, leading fintech adoption on the continent.',
    },
    {
      id: 'ainno-16',
      promptType: 'text',
      promptText: 'The traditional practice of "indigo dyeing" in which West African country has been recognized by UNESCO as Intangible Cultural Heritage?',
      answer: 'Nigeria (Yoruba indigo dyeing)',
      explanation: 'Adiré indigo cloth-making in Nigeria is a centuries-old tradition recognized globally as a masterpiece of human creativity.',
    },
    {
      id: 'ainno-17',
      promptType: 'text',
      promptText: 'Which Ethiopian mathematician and astronomer made contributions to geometry that influenced Islamic and later European scholarship?',
      answer: 'Euclid (or Ethiopian/ancient African mathematicians)',
      explanation: 'Ancient African scholars made significant contributions to mathematics and astronomy that shaped global knowledge.',
    },
    {
      id: 'ainno-18',
      promptType: 'text',
      promptText: 'Afrobeat, the music genre created by Fela Kuti, combines African rhythms with which modern music style?',
      answer: 'Jazz and funk',
      explanation: 'Afrobeat fused traditional Yoruba percussion and call-and-response vocals with jazz and funk, creating a revolutionary genre that inspired global music.',
    },
    {
      id: 'ainno-19',
      promptType: 'text',
      promptText: 'Which South African activist\'s nonviolent resistance strategies influenced which global leader\'s approach to social change?',
      answer: 'Nelson Mandela influenced global leaders',
      explanation: 'Mandela\'s philosophy of reconciliation and nonviolence inspired leaders worldwide and became a model for conflict resolution.',
    },
    {
      id: 'ainno-20',
      promptType: 'text',
      promptText: 'The "Sankofa" symbol from Ghana represents which important concept in African philosophy?',
      answer: 'Learning from the past to move forward',
      explanation: '"Sankofa" means "go back for it" in Akan, representing the importance of African heritage in shaping the future — a powerful symbol now used in global social movements.',
    },
  ],
}
