// Dish images from Wikimedia Commons (https://commons.wikimedia.org)
const DISHES = [
  {
    id: 'dish-01',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Jollof_Rice_with_Stew.jpg/1280px-Jollof_Rice_with_Stew.jpg',
    answer: 'Jollof Rice',
    acceptedAnswers: ['Jollof'],
    explanation: 'Jollof rice is a beloved one-pot rice dish cooked in tomato sauce, found across West Africa — particularly Nigeria, Ghana, and Senegal.',
  },
  {
    id: 'dish-02',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Injera_with_eight_kinds_of_stew.jpg',
    answer: 'Injera',
    explanation: 'Injera is a spongy sourdough flatbread from Ethiopia and Eritrea, used as both a plate and utensil to scoop up stews.',
  },
  {
    id: 'dish-03',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://popmenucloud.com/cdn-cgi/image/width=1920,height=1920,format=auto,fit=scale-down/gawbqmed/43462d92-f9fa-4157-892d-5a983fdebc87.jpg',
    answer: 'Egusi Soup',
    explanation: 'Egusi soup is a thick, hearty Nigerian soup made from ground melon seeds, leafy vegetables, and palm oil.',
  },
  {
    id: 'dish-04',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Bobotie%2C_South_African_dish.jpg',
    answer: 'Bobotie',
    explanation: 'Bobotie is a South African dish of spiced minced meat baked with an egg-based topping, with Cape Malay origins.',
  },
  {
    id: 'dish-05',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Tajine-marocain-un-plat-varie-et-sain_%28cropped%29.jpg',
    answer: 'Tagine',
    explanation: 'Tagine is a slow-cooked North African stew named after the conical clay pot it is cooked in, common in Morocco, Algeria, and Tunisia.',
  },
  {
    id: 'dish-06',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Thieboudienne.JPG',
    answer: 'Thieboudienne',
    explanation: 'Thieboudienne is Senegal\'s national dish — a richly flavoured rice and fish stew considered by many to be the origin of jollof rice.',
  },
  {
    id: 'dish-07',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/SuyavarietiesTX.JPG',
    answer: 'Suya',
    explanation: 'Suya is a spicy grilled skewered meat popular across West Africa, originating from the Hausa people of Nigeria and Niger.',
  },
  {
    id: 'dish-08',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/48/Ugali_%26_Sukuma_Wiki.jpg',
    answer: 'Ugali',
    explanation: 'Ugali is a stiff maize porridge that is the staple food across East Africa, particularly Kenya and Tanzania. Also called sadza in Zimbabwe.',
  },
  {
    id: 'dish-09',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Ndol%C3%A8_%C3%A0_la_viande%2C_morue_et_crevettes.jpg',
    answer: 'Ndolé',
    explanation: 'Ndolé is the national dish of Cameroon — a stew of bitter leaves, groundnuts, and meat or fish.',
  },
  {
    id: 'dish-10',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Wrapped_fufu.jpg',
    answer: 'Fufu',
    explanation: 'Fufu is a smooth, doughy staple made from boiled and pounded cassava, yam, or plantain, eaten across West and Central Africa.',
  },
  {
    id: 'dish-11',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Goat_meat_being_roasted.jpg/1280px-Goat_meat_being_roasted.jpg',
    answer: 'Nyama Choma',
    explanation: 'Nyama choma means "roasted meat" in Swahili and is the unofficial national dish of Kenya and Tanzania — typically goat or beef.',
  },
  {
    id: 'dish-12',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Quarter_Mutton_Bunny_Chow.jpg',
    answer: 'Bunny Chow',
    explanation: 'Bunny chow is a South African street food from Durban — a hollowed-out loaf of bread filled with curry, originating in the Indian community.',
  },
  {
    id: 'dish-13',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Mafe.malien.jpg',
    answer: 'Maafe',
    explanation: 'Maafe (also mafé or groundnut stew) is a rich peanut-based meat stew from West Africa, especially Senegal and Mali.',
  },
  {
    id: 'dish-14',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Sliced_Biltong.jpg',
    answer: 'Biltong',
    explanation: 'Biltong is a dried, cured meat snack from Southern Africa (South Africa, Namibia, Zimbabwe) — distinct from jerky in its vinegar and spice cure.',
  },
  {
    id: 'dish-15',
    promptType: 'image',
    promptText: 'Name this African dish.',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Chakalaka.jpg',
    answer: 'Chakalaka',
    explanation: 'Chakalaka is a spicy South African vegetable relish made with onions, tomatoes, peppers, and beans, typically served alongside bread or pap.',
  },
]

export default {
  id: 'african-dishes',
  name: 'African Dishes',
  type: 'custom-buzz',
  intro: 'A dish appears on screen. Buzz with its name.',
  rules: [
    'A photo of an African dish appears on screen',
    'Buzz in with the name of the dish',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: {
    correctPoints: 3,
    wrongPoints: -1,
    stealEnabled: true,
    correctStealPoints: 2,
    wrongStealPoints: 0,
  },
  questions: DISHES,
}
