// City images from Wikimedia Commons (https://commons.wikimedia.org)
const SKYLINES = [
  {
    id: 'sky-01',
    promptType: 'image',
    promptText: 'Which African city is this?',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Nairobi_skyline_from_Gem_Hotel.jpg/1280px-Nairobi_skyline_from_Gem_Hotel.jpg',
    answer: 'Nairobi',
    explanation: 'Nairobi is the capital and largest city of Kenya, and one of Africa\'s leading financial and technology hubs.',
  },
  {
    id: 'sky-02',
    promptType: 'image',
    promptText: 'Which African city is this?',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Johannesburg_skyline_2017.jpg',
    answer: 'Johannesburg',
    explanation: 'Johannesburg (also known as Joburg or Jozi) is the largest city in South Africa and the economic capital of the continent.',
  },
  {
    id: 'sky-03',
    promptType: 'image',
    promptText: 'Which African city is this?',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Camps_bay_%2853460319478%29_%28cropped%29.jpg/1280px-Camps_bay_%2853460319478%29_%28cropped%29.jpg',
    answer: 'Cape Town',
    explanation: 'Cape Town is South Africa\'s legislative capital, nestled at the foot of Table Mountain on the southwestern tip of the continent.',
  },
  {
    id: 'sky-04',
    promptType: 'image',
    promptText: 'Which African city is this?',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Cairo_Opera_House%2C_Al_Hurriyah_Park_and_the_Nile_river_%2814797782354%29.jpg',
    answer: 'Cairo',
    explanation: 'Cairo is the capital of Egypt and the largest city in Africa and the Arab world, home to over 20 million people in its metro area.',
  },
  {
    id: 'sky-05',
    promptType: 'image',
    promptText: 'Which African city is this?',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Casa_finance_city_6_%28cropped%29.jpg',
    answer: 'Casablanca',
    explanation: 'Casablanca is Morocco\'s largest city and its main port — the economic heart of the country despite Rabat being the capital.',
  },
  {
    id: 'sky-06',
    promptType: 'image',
    promptText: 'Which African city is this?',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Addis_in_night.jpg/1280px-Addis_in_night.jpg',
    answer: 'Addis Ababa',
    explanation: 'Addis Ababa is the capital of Ethiopia and the headquarters of the African Union. Its name means "new flower" in Amharic.',
  },
  {
    id: 'sky-07',
    promptType: 'image',
    promptText: 'Which African city is this?',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Tafa_Balewa_Square_%28Onikan%29_in_Lagos._Nigeria.jpg',
    answer: 'Lagos',
    explanation: 'Lagos is Nigeria\'s commercial capital and the most populous city in Africa, with an estimated metro population of over 15 million.',
  },
  {
    id: 'sky-08',
    promptType: 'image',
    promptText: 'Which African city is this?',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Acca.jpg',
    answer: 'Accra',
    explanation: 'Accra is the capital and largest city of Ghana, one of West Africa\'s fastest-growing urban centres.',
  },
  {
    id: 'sky-09',
    promptType: 'image',
    promptText: 'Which African city is this?',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/High_Angle_View_Of_Kigali_City_Street_on_November_29%2C_2018._Emmanuel_Kwizera.jpg',
    answer: 'Kigali',
    explanation: 'Kigali is the capital and largest city of Rwanda, widely regarded as one of the cleanest and most well-planned cities in Africa.',
  },
  {
    id: 'sky-10',
    promptType: 'image',
    promptText: 'Which African city is this?',
    mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Dakar-place-de-l%27Ind%C3%A9pendance.jpg/1280px-Dakar-place-de-l%27Ind%C3%A9pendance.jpg',
    answer: 'Dakar',
    explanation: 'Dakar is the capital of Senegal and sits at the westernmost point of mainland Africa. It is a major cultural and economic hub in West Africa.',
  },
]

export default {
  id: 'african-skylines',
  name: 'African Skylines',
  type: 'custom-buzz',
  intro: 'A city photo appears on screen. Buzz with the city name.',
  rules: [
    'A photo of an African city appears on screen',
    'Buzz in with the name of the city',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: {
    correctPoints: 3,
    wrongPoints: -1,
    stealEnabled: true,
    correctStealPoints: 2,
    wrongStealPoints: 0,
  },
  questions: SKYLINES,
}