export default {
  id: 'african-history',
  name: 'African History',
  type: 'custom-buzz',
  intro: 'Major moments, leaders, and milestones from African history.',
  rules: [
    'Host reads the question',
    'Buzz in with the answer',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: {
    correctPoints: 3,
    wrongPoints: -1,
    stealEnabled: true,
    correctStealPoints: 2,
    wrongStealPoints: 0,
  },
  questions: [
    {
      id: 'afrhist-01',
      promptType: 'text',
      promptText: 'In what year did Ghana (formerly the Gold Coast) gain independence from Great Britain?',
      answer: '1957',
      explanation: 'Ghana became independent on March 6, 1957, becoming the first sub-Saharan African country to gain independence in the colonial era.',
    },
    {
      id: 'afrhist-02',
      promptType: 'text',
      promptText: 'The 1884-85 conference that set rules for European territorial claims in Africa was held in which city?',
      answer: 'Berlin',
      explanation: 'The Berlin Conference took place in Berlin from November 15, 1884, to February 26, 1885.',
    },
    {
      id: 'afrhist-03',
      promptType: 'text',
      promptText: 'Which Ethiopian emperor led the forces that defeated Italy at the Battle of Adwa in 1896?',
      answer: 'Menelik II',
      explanation: 'At Adwa on March 1, 1896, Emperor Menelik II led Ethiopia to victory over Italy.',
    },
    {
      id: 'afrhist-04',
      promptType: 'text',
      promptText: 'What organization, founded on May 25, 1963, was later replaced by the African Union?',
      answer: 'Organization of African Unity (OAU)',
      explanation: 'The OAU was established on May 25, 1963, and was replaced by the AU in 2002.',
    },
    {
      id: 'afrhist-05',
      promptType: 'text',
      promptText: 'Tanganyika and Zanzibar united on April 26, 1964, to form what country (renamed later that year)?',
      answer: 'Tanzania',
      explanation: 'The union formed the United Republic of Tanganyika and Zanzibar, renamed Tanzania in October 1964.',
    },
    {
      id: 'afrhist-06',
      promptType: 'text',
      promptText: 'On what date was Nelson Mandela inaugurated as President of South Africa?',
      answer: 'May 10, 1994',
      explanation: 'Mandela was inaugurated on May 10, 1994, following South Africa\'s first democratic elections.',
    },
    {
      id: 'afrhist-07',
      promptType: 'text',
      promptText: 'Great Zimbabwe, the major stone-ruin city, is in which present-day country?',
      answer: 'Zimbabwe',
      explanation: 'Great Zimbabwe lies in southeastern Zimbabwe and was the center of a major trading power from the 11th to the 15th centuries.',
    },
    {
      id: 'afrhist-08',
      promptType: 'text',
      promptText: 'Which river\'s annual flooding supported agriculture in ancient Egypt?',
      answer: 'Nile River',
      explanation: 'Ancient Egypt depended on the Nile\'s annual inundation to sustain its agricultural population.',
    },
    {
      id: 'afrhist-09',
      promptType: 'text',
      promptText: 'Queen Nzinga ruled Ndongo and Matamba in which present-day country?',
      answer: 'Angola',
      explanation: 'Nzinga ruled in the region of present-day Angola during the 17th century and resisted colonial pressure.',
    },
    {
      id: 'afrhist-10',
      promptType: 'text',
      promptText: 'In which year did Algeria gain independence from France?',
      answer: '1962',
      explanation: 'Algeria\'s listed independence date is July 5, 1962.',
    },
    {
      id: 'afrhist-11',
      promptType: 'text',
      promptText: 'Which Malian ruler became famous for his pilgrimage to Mecca in 1324?',
      answer: 'Mansa Musa (Musa I)',
      explanation: 'Musa I of Mali became famous across the wider world after his 1324 pilgrimage to Mecca.',
    },
    {
      id: 'afrhist-12',
      promptType: 'text',
      promptText: 'Before independence, modern Ghana was known by what colonial name?',
      answer: 'Gold Coast',
      explanation: 'The British colony called the Gold Coast gained independence in 1957 and became Ghana.',
    },
  ],
}
