export default {
  id: 'before-famous-african-artists',
  name: 'Before They Were Famous',
  type: 'custom-buzz',
  intro: 'Watch early-era clips and guess the artist before their global breakout years.',
  rules: [
    'Host plays the clip; teams buzz with the artist name',
    'Artist name only is required',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: [
    { label: 'Correct artist', points: 3, phase: 'normal' },
    { label: 'Wrong answer', points: -1, phase: 'normal' },
    { label: 'Correct steal', points: 2, phase: 'steal' },
    { label: 'Wrong steal', points: 0, phase: 'steal' },
  ],
  questions: [
    {
      id: 'btwf-01',
      promptType: 'video',
      promptText: 'Early-era clip: name the artist.',
      mediaUrl: 'https://www.youtube.com/watch?v=Rcy_JnJQPE0&start=35',
      answer: 'Wizkid',
      explanation: '"Holla at Your Boy" is from Wizkid\'s early breakout era.',
    },
    {
      id: 'btwf-02',
      promptType: 'video',
      promptText: 'Early-era clip: name the artist.',
      mediaUrl: 'https://www.youtube.com/watch?v=6CyUo6rQ2rU&start=28',
      answer: 'Davido',
      explanation: '"Dami Duro" helped launch Davido into mainstream stardom.',
    },
    {
      id: 'btwf-03',
      promptType: 'video',
      promptText: 'Early-era clip: name the artist.',
      mediaUrl: 'https://www.youtube.com/watch?v=t7tc1o43soM&start=30',
      answer: 'Burna Boy',
      explanation: '"Like To Party" is one of Burna Boy\'s foundational early hits.',
    },
    {
      id: 'btwf-04',
      promptType: 'video',
      promptText: 'Early-era clip: name the artist.',
      mediaUrl: 'https://www.youtube.com/watch?v=4QcytP8FQwQ&start=32',
      answer: 'Yemi Alade',
      explanation: '"Johnny" drove Yemi Alade\'s continental recognition.',
    },
    {
      id: 'btwf-05',
      promptType: 'video',
      promptText: 'Early-era clip: name the artist.',
      mediaUrl: 'https://www.youtube.com/watch?v=zUU1bIWpH5c&start=20',
      answer: 'Rema',
      explanation: '"Dumebi" became one of Rema\'s first major crossover records.',
    },
    {
      id: 'btwf-06',
      promptType: 'video',
      promptText: 'Early-era clip: name the artist.',
      mediaUrl: 'https://www.youtube.com/watch?v=HYJFTodtu5k&start=18',
      answer: 'Tiwa Savage',
      explanation: '"Wanted" belongs to Tiwa Savage\'s earlier solo run.',
    },
    {
      id: 'btwf-07',
      promptType: 'video',
      promptText: 'Early-era clip: name the artist.',
      mediaUrl: 'https://www.youtube.com/watch?v=64riif8FfNI&start=35',
      answer: 'Diamond Platnumz',
      explanation: '"Number One" is one of Diamond\'s classic early-era bongo hits.',
    },
    {
      id: 'btwf-08',
      promptType: 'video',
      promptText: 'Early-era clip: name the artist.',
      mediaUrl: 'https://www.youtube.com/watch?v=ipZvlG-wwWk&start=22',
      answer: 'Sarkodie',
      explanation: '"Adonai" became one of Sarkodie\'s signature songs.',
    },
    {
      id: 'btwf-09',
      promptType: 'video',
      promptText: 'Early-era clip: name the artist.',
      mediaUrl: 'https://www.youtube.com/watch?v=sqflXTvth3s&start=24',
      answer: 'Davido',
      explanation: '"Skelewu" was another key early Davido era anthem.',
    },
    {
      id: 'btwf-10',
      promptType: 'video',
      promptText: 'Early-era clip: name the artist.',
      mediaUrl: 'https://www.youtube.com/watch?v=7V2LkSoA8F4&start=22',
      answer: 'CKay',
      explanation: '"Love Nwantiti" predates CKay\'s full global breakout wave.',
    },
  ],
}
