export default {
  id: 'before-famous-african-artists',
  name: 'Before They Were Famous',
  type: 'custom-buzz',
  intro: 'Look at old-era photos and guess the artist before their global breakout years.',
  rules: [
    'Host shows the photo; teams buzz with the artist name',
    'Artist name only is required',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: {
    correctPoints: 3,
    correctLabel: 'Correct artist',
    wrongPoints: -1,
    stealEnabled: true,
    correctStealPoints: 2,
    wrongStealPoints: 0,
  },
  questions: [
    {
      id: 'btwf-01',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://www.nairaland.com/attachments/5079651_wiskidfriend_jpeg30e4b5f56554fd702cc9ec0006e0ecdf',
      answer: 'Wizkid',
      explanation: '"Holla at Your Boy" is from Wizkid\'s early breakout era.',
    },
    {
      id: 'btwf-02',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhP9G1_9RhDFGZhYK9IbTBe-D8r5XAuVki24rNFe4t9eUIFcWtwXnTuSPZ5PKwLWVD4FrATswsTg1_GCTam6fFyyLKQZceMynOFBHVkODME2tZyQyChfNZWatmGHNCg7lnswF2s8Y5l4N0/s1600/Untitled-2.png',
      answer: 'Davido',
      explanation: '"Dami Duro" helped launch Davido into mainstream stardom.',
    },
    {
      id: 'btwf-03',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://cdn.modernghana.com/content__/640/457/burnaboygirlfriend.jpg',
      answer: 'Burna Boy',
      explanation: '"Like To Party" is one of Burna Boy\'s foundational early hits.',
    },
    {
      id: 'btwf-04',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://womenofrubies.com/wp-content/uploads/2017/02/download-2.jpg',
      answer: 'Yemi Alade',
      explanation: '"Johnny" drove Yemi Alade\'s continental recognition.',
    },
    {
      id: 'btwf-05',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://college.berklee.edu/sites/default/files/d7/bcm/news/216/tiwasavage1.png?fv=WViEhNpV',
      answer: 'Tiwa Savage',
      explanation: '"Wanted" belongs to Tiwa Savage\'s earlier solo run.',
    },
    {
      id: 'btwf-06',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://www.ghafla.co.ke/ke/wp-content/uploads/sites/4/2017/10/chibu3.png',
      answer: 'Diamond Platnumz',
      explanation: '"Number One" is one of Diamond\'s classic early-era bongo hits.',
    },
    {
      id: 'btwf-07',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://www.nairaland.com/attachments/2132531_sark_jpegaa4ed822509932198886a42c5ea6b300',
      answer: 'Sarkodie',
      explanation: '"Adonai" became one of Sarkodie\'s signature songs.',
    },
    {
      id: 'btwf-08',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://i.ytimg.com/vi/WtElLKoQoyo/hqdefault.jpg',
      answer: 'Rema',
      explanation: '"Dumebi" became one of Rema\'s first major crossover records.',
    },
    {
      id: 'btwf-09',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://limitlessmotivation1.wordpress.com/wp-content/uploads/2022/04/wp-1649518898953.jpg?w=926',
      answer: 'Black Sherif',
      explanation: '"Kwaku the Traveller" accelerated Black Sherif\'s breakout momentum.',
    },
    {
      id: 'btwf-10',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://www.ghafla.co.ke/images/sauti_tbt.jpg',
      answer: 'Sauti Sol',
      explanation: '"Sura Yako" remains one of Sauti Sol\'s defining early-era global songs.',
    },
    {
      id: 'btwf-11',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://assets.vogue.com/photos/58c40e06fec5690f5e1c0f3a/master/pass/01-mr-eazi.jpg',
      answer: 'Mr Eazi',
      explanation: '"Skin Tight" helped establish Mr Eazi\'s early pan-African visibility.',
    },
    {
      id: 'btwf-12',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://www.nairaland.com/attachments/3669973_sqaure_jpega5b83c7d23819100afa10db1296b0deb',
      answer: 'P-Square',
      explanation: '"Bizzy Body" and "Do Me" were key songs from P-Square\'s rise era.',
    },
    {
      id: 'btwf-13',
      promptType: 'image',
      promptText: 'Old photo: name the artist.',
      mediaUrl: 'https://www.bellanaija.com/wp-content/uploads/2019/07/Sho-Madjozi-1000x600.jpg',
      answer: 'Sho Madjozi',
      explanation: '"John Cena" pushed Sho Madjozi into broader international recognition.',
    },
  ],
}
