export default {
  id: 'before-and-after',
  name: 'Before & After',
  type: 'custom-buzz',
  intro: 'Two African events — buzz with "Before" or "After".',
  rules: [
    'The host reads two African historical events',
    'Buzz in with "Before" if the first happened before the second, or "After" if it came later',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: [
    { label: 'Correct answer', points: 3, phase: 'normal' },
    { label: 'Wrong answer', points: -1, phase: 'normal' },
    { label: 'Correct steal', points: 2, phase: 'steal' },
    { label: 'Wrong steal', points: 0, phase: 'steal' },
  ],
  questions: [
    {
      id: 'bna-01',
      promptType: 'text',
      promptText: 'Did Ghana gain independence before or after Nigeria?',
      answer: 'Before',
      explanation: 'Ghana gained independence in March 1957; Nigeria followed in October 1960.',
    },
    {
      id: 'bna-02',
      promptType: 'text',
      promptText: 'Was Nelson Mandela released from prison before or after South Africa held its first democratic election?',
      answer: 'Before',
      explanation: 'Mandela was released in February 1990. South Africa\'s first democratic election was in April 1994.',
    },
    {
      id: 'bna-03',
      promptType: 'text',
      promptText: 'Did the Rwandan genocide happen before or after the start of the Sierra Leone Civil War?',
      answer: 'After',
      explanation: 'The Sierra Leone Civil War began in March 1991. The Rwandan genocide occurred in April–July 1994.',
    },
    {
      id: 'bna-04',
      promptType: 'text',
      promptText: 'Was the African Union founded before or after the Organisation of African Unity?',
      answer: 'After',
      explanation: 'The Organisation of African Unity (OAU) was founded in 1963. It was replaced by the African Union in 2002.',
    },
    {
      id: 'bna-05',
      promptType: 'text',
      promptText: 'Was Fela Kuti born before or after Miriam Makeba?',
      answer: 'After',
      explanation: 'Miriam Makeba was born in March 1932. Fela Kuti was born in October 1938.',
    },
    {
      id: 'bna-06',
      promptType: 'text',
      promptText: 'Did the opening of the Suez Canal happen before or after the Berlin Conference that divided Africa among European powers?',
      answer: 'Before',
      explanation: 'The Suez Canal opened in 1869. The Berlin Conference (Scramble for Africa) took place in 1884–1885.',
    },
    {
      id: 'bna-07',
      promptType: 'text',
      promptText: 'Was Chinua Achebe\'s "Things Fall Apart" published before or after Wole Soyinka won the Nobel Prize in Literature?',
      answer: 'Before',
      explanation: 'Things Fall Apart was published in 1958. Wole Soyinka became the first African to win the Nobel Prize in Literature in 1986.',
    },
    {
      id: 'bna-08',
      promptType: 'text',
      promptText: 'Did apartheid officially begin in South Africa before or after the Sharpeville massacre?',
      answer: 'Before',
      explanation: 'Apartheid was officially instituted in 1948 when the National Party came to power. The Sharpeville massacre occurred in March 1960.',
    },
    {
      id: 'bna-09',
      promptType: 'text',
      promptText: 'Did the Democratic Republic of Congo gain independence before or after Patrice Lumumba was assassinated?',
      answer: 'Before',
      explanation: 'The DRC (then Congo-Léopoldville) gained independence from Belgium in June 1960. Lumumba was assassinated in January 1961.',
    },
    {
      id: 'bna-10',
      promptType: 'text',
      promptText: 'Was the Aswan High Dam in Egypt completed before or after the Six-Day War?',
      answer: 'After',
      explanation: 'The Six-Day War was fought in June 1967. Egypt\'s Aswan High Dam was completed in 1970.',
    },
    {
      id: 'bna-11',
      promptType: 'text',
      promptText: 'Did Zimbabwe gain independence before or after Mozambique?',
      answer: 'After',
      explanation: 'Mozambique gained independence from Portugal in June 1975. Zimbabwe gained independence from Britain in April 1980.',
    },
    {
      id: 'bna-12',
      promptType: 'text',
      promptText: 'Did the first Pan-African Conference take place before or after Ghana gained independence?',
      answer: 'Before',
      explanation: 'The first Pan-African Conference was held in London in 1900 (organised by Henry Sylvester Williams). The first Pan-African Congress, organised by W.E.B. Du Bois, was in 1919. Both predate Ghana\'s independence in 1957.',
    },
    {
      id: 'bna-13',
      promptType: 'text',
      promptText: 'Did Wangari Maathai win the Nobel Peace Prize before or after South Africa hosted the FIFA World Cup?',
      answer: 'Before',
      explanation: 'Wangari Maathai won the Nobel Peace Prize in 2004. South Africa hosted the 2010 FIFA World Cup.',
    },
    {
      id: 'bna-14',
      promptType: 'text',
      promptText: 'Did Kenya gain independence before or after Tanzania?',
      answer: 'After',
      explanation: 'Tanganyika (mainland Tanzania) gained independence in December 1961. Kenya gained independence in December 1963.',
    },
    {
      id: 'bna-15',
      promptType: 'text',
      promptText: 'Did Zambia gain independence before or after Zimbabwe?',
      answer: 'Before',
      explanation: 'Zambia (formerly Northern Rhodesia) gained independence in October 1964. Zimbabwe gained independence in April 1980.',
    },
  ],
}
