export default {
  id: 'capital-cities',
  name: 'Capital Cities',
  type: 'custom-buzz',
  intro: 'Quick-fire geography. Host reads the country; teams buzz with the capital city.',
  rules: [
    'Host reads the country name',
    'Buzz in with the capital city',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: [
    { label: 'Correct answer', points: 3, phase: 'normal' },
    { label: 'Wrong answer', points: -1, phase: 'normal' },
    { label: 'Correct steal', points: 2, phase: 'steal' },
    { label: 'Wrong steal', points: 0, phase: 'steal' },
  ],
  questions: [
    {
      id: 'cap-01',
      promptType: 'text',
      promptText: 'What is the capital city of Mauritania?',
      answer: 'Nouakchott',
      explanation: 'Nouakchott is Mauritania\'s capital on the Atlantic coast.',
    },
    {
      id: 'cap-02',
      promptType: 'text',
      promptText: 'What is the capital city of Chad?',
      answer: "N'Djamena",
      explanation: "N'Djamena sits where the Chari and Logone rivers meet.",
    },
    {
      id: 'cap-03',
      promptType: 'text',
      promptText: 'What is the capital city of Burkina Faso?',
      answer: 'Ouagadougou',
      explanation: 'Ouagadougou is often shortened to "Ouaga".',
    },
    {
      id: 'cap-04',
      promptType: 'text',
      promptText: 'What is the capital city of Madagascar?',
      answer: 'Antananarivo',
      explanation: 'Antananarivo is commonly nicknamed "Tana".',
    },
    {
      id: 'cap-05',
      promptType: 'text',
      promptText: 'What is the official capital city of Benin?',
      answer: 'Porto-Novo',
      explanation: 'Porto-Novo is the official capital, though Cotonou is the government and economic center.',
    },
    {
      id: 'cap-06',
      promptType: 'text',
      promptText: 'What is the capital city of Comoros?',
      answer: 'Moroni',
      explanation: 'Moroni is on Grande Comore island.',
    },
    {
      id: 'cap-07',
      promptType: 'text',
      promptText: 'What is the capital city of Equatorial Guinea?',
      answer: 'Malabo',
      explanation: 'Malabo is on Bioko Island.',
    },
    {
      id: 'cap-08',
      promptType: 'text',
      promptText: 'What is the capital city of Guinea-Bissau?',
      answer: 'Bissau',
      explanation: 'Bissau is the country\'s largest city and port.',
    },
    {
      id: 'cap-09',
      promptType: 'text',
      promptText: 'What is the capital city of Sao Tome and Principe?',
      answer: 'Sao Tome',
      explanation: 'Sao Tome city is on Sao Tome Island and is the national capital.',
    },
    {
      id: 'cap-10',
      promptType: 'text',
      promptText: 'What is the capital city of Seychelles?',
      answer: 'Victoria',
      explanation: 'Victoria is one of the smallest national capitals in the world.',
    },
    {
      id: 'cap-11',
      promptType: 'text',
      promptText: 'What is the administrative capital of Eswatini?',
      answer: 'Mbabane',
      explanation: 'Eswatini has two capitals: Mbabane (administrative) and Lobamba (legislative/royal).',
    },
    {
      id: 'cap-12',
      promptType: 'text',
      promptText: 'What is the capital city of Eritrea?',
      answer: 'Asmara',
      explanation: 'Asmara is known for its modernist architecture from the Italian colonial era.',
    },
  ],
}
