export default {
  id: 'capital-cities',
  name: 'Capital Cities',
  type: 'custom-buzz',
  intro: 'Quick-fire geography. Host reads the country; teams buzz with the capital city.',
  rules: [
    'Host reads the country name',
    'Buzz in with the capital city',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: {
    correctPoints: 3,
    wrongPoints: -1,
    stealEnabled: true,
    correctStealPoints: 2,
    wrongStealPoints: 0,
  },
  questions: [
    {
      id: 'cap-01',
      promptType: 'text',
      promptText: 'What is the capital city of Mauritania?',
      answer: 'Nouakchott',
      explanation: 'Nouakchott is Mauritania\'s capital on the Atlantic coast.',
    },
    {
      id: 'cap-02',
      promptType: 'text',
      promptText: 'What is the capital city of Chad?',
      answer: "N'Djamena",
      explanation: "N'Djamena sits where the Chari and Logone rivers meet.",
    },
    {
      id: 'cap-03',
      promptType: 'text',
      promptText: 'What is the capital city of Burkina Faso?',
      answer: 'Ouagadougou',
      explanation: 'Ouagadougou is often shortened to "Ouaga".',
    },
    {
      id: 'cap-04',
      promptType: 'text',
      promptText: 'What is the capital city of Madagascar?',
      answer: 'Antananarivo',
      explanation: 'Antananarivo is commonly nicknamed "Tana".',
    },
    {
      id: 'cap-05',
      promptType: 'text',
      promptText: 'What is the official capital city of Benin?',
      answer: 'Porto-Novo',
      explanation: 'Porto-Novo is the official capital, though Cotonou is the government and economic center.',
    },
    {
      id: 'cap-06',
      promptType: 'text',
      promptText: 'What is the capital city of Comoros?',
      answer: 'Moroni',
      explanation: 'Moroni is on Grande Comore island.',
    },
    {
      id: 'cap-07',
      promptType: 'text',
      promptText: 'What is the capital city of Equatorial Guinea?',
      answer: 'Malabo',
      explanation: 'Malabo is on Bioko Island.',
    },
    {
      id: 'cap-08',
      promptType: 'text',
      promptText: 'What is the capital city of Guinea-Bissau?',
      answer: 'Bissau',
      explanation: 'Bissau is the country\'s largest city and port.',
    },
    {
      id: 'cap-09',
      promptType: 'text',
      promptText: 'What is the capital city of Sao Tome and Principe?',
      answer: 'Sao Tome',
      explanation: 'Sao Tome city is on Sao Tome Island and is the national capital.',
    },
    {
      id: 'cap-10',
      promptType: 'text',
      promptText: 'What is the capital city of Seychelles?',
      answer: 'Victoria',
      explanation: 'Victoria is one of the smallest national capitals in the world.',
    },
    {
      id: 'cap-11',
      promptType: 'text',
      promptText: 'What is the administrative capital of Eswatini?',
      answer: 'Mbabane',
      explanation: 'Eswatini has two capitals: Mbabane (administrative) and Lobamba (legislative/royal).',
    },
    {
      id: 'cap-12',
      promptType: 'text',
      promptText: 'What is the capital city of Eritrea?',
      answer: 'Asmara',
      explanation: 'Asmara is known for its modernist architecture from the Italian colonial era.',
    },
    {
      id: 'cap-13',
      promptType: 'text',
      promptText: 'What is the capital city of Algeria?',
      answer: 'Algiers',
      explanation: 'Algiers sits on the Mediterranean coast and is one of the largest cities in Africa.',
    },
    {
      id: 'cap-14',
      promptType: 'text',
      promptText: 'What is the capital city of Angola?',
      answer: 'Luanda',
      explanation: 'Luanda is Angola\'s largest city and main port on the Atlantic coast.',
    },
    {
      id: 'cap-15',
      promptType: 'text',
      promptText: 'What is the capital city of Botswana?',
      answer: 'Gaborone',
      explanation: 'Gaborone is one of Africa\'s fastest-growing cities.',
    },
    {
      id: 'cap-16',
      promptType: 'text',
      promptText: 'What is the capital city of Burundi?',
      answer: 'Gitega',
      explanation: 'Gitega replaced Bujumbura as the official capital in 2019.',
    },
    {
      id: 'cap-17',
      promptType: 'text',
      promptText: 'What is the capital city of Cameroon?',
      answer: 'Yaoundé',
      explanation: 'Yaoundé is the political capital; Douala is the larger economic hub.',
    },
    {
      id: 'cap-18',
      promptType: 'text',
      promptText: 'What is the capital city of Cape Verde?',
      answer: 'Praia',
      explanation: 'Praia is on Santiago island, the largest of the Cape Verde archipelago.',
    },
    {
      id: 'cap-19',
      promptType: 'text',
      promptText: 'What is the capital city of the Central African Republic?',
      answer: 'Bangui',
      explanation: 'Bangui sits on the Ubangi River on the border with the DRC.',
    },
    {
      id: 'cap-20',
      promptType: 'text',
      promptText: 'What is the capital city of the Republic of the Congo?',
      answer: 'Brazzaville',
      explanation: 'Brazzaville faces Kinshasa across the Congo River — the two capitals are the closest in the world.',
    },
    {
      id: 'cap-21',
      promptType: 'text',
      promptText: 'What is the capital city of the Democratic Republic of the Congo?',
      answer: 'Kinshasa',
      explanation: 'Kinshasa is the third-largest city in Africa and faces Brazzaville across the Congo River.',
    },
    {
      id: 'cap-22',
      promptType: 'text',
      promptText: 'What is the capital city of Djibouti?',
      answer: 'Djibouti',
      explanation: 'The country and its capital share the same name.',
    },
    {
      id: 'cap-23',
      promptType: 'text',
      promptText: 'What is the capital city of Egypt?',
      answer: 'Cairo',
      explanation: 'Cairo is the largest city in Africa and the Arab world.',
    },
    {
      id: 'cap-24',
      promptType: 'text',
      promptText: 'What is the capital city of Ethiopia?',
      answer: 'Addis Ababa',
      explanation: 'Addis Ababa means "new flower" in Amharic and is also the headquarters of the African Union.',
    },
    {
      id: 'cap-25',
      promptType: 'text',
      promptText: 'What is the capital city of Gabon?',
      answer: 'Libreville',
      explanation: 'Libreville means "free town" in French, named by freed slaves in 1848.',
    },
    {
      id: 'cap-26',
      promptType: 'text',
      promptText: 'What is the capital city of The Gambia?',
      answer: 'Banjul',
      explanation: 'Banjul is on St. Mary\'s Island where the Gambia River meets the Atlantic.',
    },
    {
      id: 'cap-27',
      promptType: 'text',
      promptText: 'What is the capital city of Ghana?',
      answer: 'Accra',
      explanation: 'Accra is on the Gulf of Guinea and is one of the fastest-growing cities on the continent.',
    },
    {
      id: 'cap-28',
      promptType: 'text',
      promptText: 'What is the capital city of Guinea?',
      answer: 'Conakry',
      explanation: 'Conakry is built on the Kaloum Peninsula and Tombo Island.',
    },
    {
      id: 'cap-29',
      promptType: 'text',
      promptText: 'What is the official capital city of Ivory Coast?',
      answer: 'Yamoussoukro',
      explanation: 'Yamoussoukro is the official capital since 1983. Abidjan remains the economic and administrative hub.',
    },
    {
      id: 'cap-30',
      promptType: 'text',
      promptText: 'What is the capital city of Kenya?',
      answer: 'Nairobi',
      explanation: 'Nairobi is one of the fastest-growing cities in the world and is known as "The Green City in the Sun".',
    },
    {
      id: 'cap-31',
      promptType: 'text',
      promptText: 'What is the capital city of Lesotho?',
      answer: 'Maseru',
      explanation: 'Maseru is on the Caledon River on the western border with South Africa.',
    },
    {
      id: 'cap-32',
      promptType: 'text',
      promptText: 'What is the capital city of Liberia?',
      answer: 'Monrovia',
      explanation: 'Monrovia was named after U.S. President James Monroe and is one of the oldest capital cities in sub-Saharan Africa.',
    },
    {
      id: 'cap-33',
      promptType: 'text',
      promptText: 'What is the capital city of Libya?',
      answer: 'Tripoli',
      explanation: 'Tripoli is on the Mediterranean coast and is one of the oldest cities in the world.',
    },
    {
      id: 'cap-34',
      promptType: 'text',
      promptText: 'What is the capital city of Malawi?',
      answer: 'Lilongwe',
      explanation: 'Lilongwe replaced Zomba as the capital in 1975.',
    },
    {
      id: 'cap-35',
      promptType: 'text',
      promptText: 'What is the capital city of Mali?',
      answer: 'Bamako',
      explanation: 'Bamako is on the Niger River and is one of Africa\'s fastest-growing cities.',
    },
    {
      id: 'cap-36',
      promptType: 'text',
      promptText: 'What is the capital city of Mauritius?',
      answer: 'Port Louis',
      explanation: 'Port Louis is the financial center of Mauritius and one of Africa\'s wealthiest cities per capita.',
    },
    {
      id: 'cap-37',
      promptType: 'text',
      promptText: 'What is the capital city of Morocco?',
      answer: 'Rabat',
      explanation: 'Rabat is the political capital; Casablanca is the larger economic hub.',
    },
    {
      id: 'cap-38',
      promptType: 'text',
      promptText: 'What is the capital city of Mozambique?',
      answer: 'Maputo',
      explanation: 'Maputo was previously called Lourenço Marques during Portuguese colonial rule.',
    },
    {
      id: 'cap-39',
      promptType: 'text',
      promptText: 'What is the capital city of Namibia?',
      answer: 'Windhoek',
      explanation: 'Windhoek is centrally located and was founded as a German colonial town.',
    },
    {
      id: 'cap-40',
      promptType: 'text',
      promptText: 'What is the capital city of Niger?',
      answer: 'Niamey',
      explanation: 'Niamey is on the Niger River and is the country\'s only large city.',
    },
    {
      id: 'cap-41',
      promptType: 'text',
      promptText: 'What is the capital city of Nigeria?',
      answer: 'Abuja',
      explanation: 'Abuja replaced Lagos as the capital in 1991. It was purpose-built as a federal capital territory.',
    },
    {
      id: 'cap-42',
      promptType: 'text',
      promptText: 'What is the capital city of Rwanda?',
      answer: 'Kigali',
      explanation: 'Kigali is one of the cleanest and most orderly cities in Africa.',
    },
    {
      id: 'cap-43',
      promptType: 'text',
      promptText: 'What is the capital city of Senegal?',
      answer: 'Dakar',
      explanation: 'Dakar is the westernmost point of mainland Africa.',
    },
    {
      id: 'cap-44',
      promptType: 'text',
      promptText: 'What is the capital city of Sierra Leone?',
      answer: 'Freetown',
      explanation: 'Freetown was founded in 1792 as a home for freed slaves.',
    },
    {
      id: 'cap-45',
      promptType: 'text',
      promptText: 'What is the capital city of Somalia?',
      answer: 'Mogadishu',
      explanation: 'Mogadishu is one of the oldest cities in sub-Saharan Africa and the largest in Somalia.',
    },
    {
      id: 'cap-46',
      promptType: 'text',
      promptText: 'What is the administrative capital of South Africa?',
      answer: 'Pretoria',
      explanation: 'South Africa has three capitals: Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial).',
    },
    {
      id: 'cap-47',
      promptType: 'text',
      promptText: 'What is the capital city of South Sudan?',
      answer: 'Juba',
      explanation: 'Juba is on the White Nile and became a capital when South Sudan gained independence in 2011.',
    },
    {
      id: 'cap-48',
      promptType: 'text',
      promptText: 'What is the capital city of Sudan?',
      answer: 'Khartoum',
      explanation: 'Khartoum sits at the confluence of the Blue Nile and White Nile rivers.',
    },
    {
      id: 'cap-49',
      promptType: 'text',
      promptText: 'What is the official capital city of Tanzania?',
      answer: 'Dodoma',
      explanation: 'Dodoma has been the official capital since 1996, though Dar es Salaam remains the commercial center.',
    },
    {
      id: 'cap-50',
      promptType: 'text',
      promptText: 'What is the capital city of Togo?',
      answer: 'Lomé',
      explanation: 'Lomé is a major West African port city on the Gulf of Guinea.',
    },
    {
      id: 'cap-51',
      promptType: 'text',
      promptText: 'What is the capital city of Tunisia?',
      answer: 'Tunis',
      explanation: 'Tunis is adjacent to the ancient ruins of Carthage.',
    },
    {
      id: 'cap-52',
      promptType: 'text',
      promptText: 'What is the capital city of Uganda?',
      answer: 'Kampala',
      explanation: 'Kampala is built on seven hills and is known as "The Pearl of Africa\'s capital".',
    },
    {
      id: 'cap-53',
      promptType: 'text',
      promptText: 'What is the capital city of Zambia?',
      answer: 'Lusaka',
      explanation: 'Lusaka replaced Livingstone as the capital in 1935.',
    },
    {
      id: 'cap-54',
      promptType: 'text',
      promptText: 'What is the capital city of Zimbabwe?',
      answer: 'Harare',
      explanation: 'Harare was formerly called Salisbury during the colonial era.',
    },
  ],
}
