export default {
  label: 'Round 1',
  name: 'Charades',
  type: 'charades',
  intro: 'Act out African and diasporic cultural references — no words, no mouthing, no pointing at objects in the room.',
  rules: [
    'Teams take turns — one person acts, the rest of the team guesses',
    'No speaking, mouthing words, or spelling things out',
    'Host decides timing per turn',
    '3 points for a correct answer by the acting team',
    'If time runs out, other teams can steal by buzzing in',
    '+2 for a correct steal, -1 for a wrong steal',
  ],
  scoring: [
    { label: 'Correct answer', points: 3 },
    { label: 'Correct steal',  points: 2 },
    { label: 'Wrong steal',    points: -1 },
  ],
  questions: [
    { id: 'c1',  phrase: 'Jollof Rice Debate' },
    { id: 'c2',  phrase: 'Nollywood Movie Star' },
    { id: 'c3',  phrase: 'African Aunty at a Party' },
    { id: 'c4',  phrase: 'Crossing the Atlantic' },
    { id: 'c5',  phrase: 'Sunday Church Service' },
    { id: 'c6',  phrase: 'Braiding Hair' },
    { id: 'c7',  phrase: 'Market Haggling' },
    { id: 'c8',  phrase: 'Afrobeats Dance Move' },
    { id: 'c9',  phrase: 'Getting a Visa' },
    { id: 'c10', phrase: 'Sending Money Back Home' },
  ],
}
