export default {
  label: 'Round 1',
  name: 'Charades',
  type: 'charades',
  intro: 'Act out African and diasporic cultural references — no words, no mouthing, no pointing at objects in the room.',
  rules: [
    'Round robin — one person from each team acts while their team guesses',
    'No speaking, mouthing words, or spelling things out',
    '90 seconds on the timer — start it when the phrase is revealed',
    'Correct answer: +3 pts',
    'If time runs out, one steal is open — buzz in to attempt',
    'Correct steal: +2 pts — wrong steal: no penalty',
  ],
  scoring: [
    { label: 'Correct answer', points: 3 },
    { label: 'Wrong answer',  points: 0 },
    { label: 'Correct steal',  points: 2 },
    { label: 'Wrong steal',    points: 0 },
  ],
  questions: [
    { id: 'c1', phrase: 'Braiding Hair' },
    { id: 'c2', phrase: 'Azonto Dance' },
    { id: 'c3', phrase: 'Pounding Food (Fufu / Yam / Cassava)' },
    { id: 'c4', phrase: 'Power Outage' },
    { id: 'c5', phrase: 'Parents Scolding You' },
    { id: 'c6', phrase: 'Stuck in Traffic'},
    { id: 'c7', phrase: 'Peeling Plantain' },
    { id: 'c8', phrase: 'Roadside Mechanic' },
    { id: 'c9', phrase: 'Baby on Back' },
    { id: 'c10', phrase: 'Fetching Water' },
    { id: 'c11', phrase: 'Taking Public Transport (Trotro / Danfo / Matatu etc)' },
    { id: 'c12', phrase: 'Waving Down a Taxi' },
    { id: 'c13', phrase: 'Waiting in a Long Queue' },
    { id: 'c14', phrase: 'Sweeping the Compound' },
    { id: 'c15', phrase: 'Roadside Hawkers / Street Sellers' },
    { id: 'c16', phrase: 'Dodging Potholes' },
  ],
}
