export default {
  id: 'flag-trivia-descriptions',
  name: 'Flag Trivia (Verbal Clues)',
  type: 'custom-buzz',
  intro: 'No image this time. Listen to the clue and name the country.',
  rules: [
    'Host reads the flag clue out loud',
    'Buzz in with the country',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: {
    correctPoints: 3,
    wrongPoints: -1,
    stealEnabled: true,
    correctStealPoints: 2,
    wrongStealPoints: 0,
  },
  questions: [
    {
      id: 'flag-trivia-01',
      promptType: 'text',
      promptText: 'Which African country has the only national flag in the world featuring an AK-47 rifle?',
      answer: 'Mozambique',
      explanation: 'Mozambique’s emblem includes a book, hoe, and AK-47 on a yellow star.',
    },
    {
      id: 'flag-trivia-02',
      promptType: 'text',
      promptText: 'Which country’s flag has a black, red, and green horizontal tricolor with a central shield and crossed spears?',
      answer: 'Kenya',
      explanation: 'The shield and spears are a defining symbol on Kenya’s flag.',
    },
    {
      id: 'flag-trivia-03',
      promptType: 'text',
      promptText: 'Which country’s flag has a blue top band, yellow middle band, green bottom band, and a golden sun in the top-right corner?',
      answer: 'Rwanda',
      explanation: 'Rwanda’s flag was adopted in 2001 and features a 24-ray sun.',
    },
    {
      id: 'flag-trivia-04',
      promptType: 'text',
      promptText: 'Which African flag is red with a centered green five-pointed star?',
      answer: 'Morocco',
      explanation: 'The green pentagram (Seal of Solomon) is centered on Morocco’s red field.',
    },
    {
      id: 'flag-trivia-05',
      promptType: 'text',
      promptText: 'Which country’s flag has three vertical stripes green, yellow, red with a green star centered on the yellow stripe?',
      answer: 'Senegal',
      explanation: 'Senegal’s tricolor resembles other Pan-African designs but includes a central green star.',
    },
    {
      id: 'flag-trivia-06',
      promptType: 'text',
      promptText: 'Which country’s flag has a diagonal black band edged in yellow, separating green and blue triangles?',
      answer: 'Tanzania',
      explanation: 'The black band with yellow borders is Tanzania’s key identifying feature.',
    },
    {
      id: 'flag-trivia-07',
      promptType: 'text',
      promptText: 'Which country’s flag has ten yellow stars in a circle over blue and white horizontal stripes?',
      answer: 'Cape Verde',
      explanation: 'Cape Verde’s ring of stars represents its islands and ties to Atlantic symbolism.',
    },
    {
      id: 'flag-trivia-08',
      promptType: 'text',
      promptText: 'Which country’s flag is light blue with a black horizontal stripe outlined in white?',
      answer: 'Botswana',
      explanation: 'Botswana’s clean, high-contrast stripe pattern is distinctive in Africa.',
    },
    {
      id: 'flag-trivia-09',
      promptType: 'text',
      promptText: 'Which country’s flag has a horizontal red-blue-red layout with a white triangle at the hoist and a red star inside the triangle?',
      answer: 'Djibouti',
      explanation: 'Djibouti’s flag combines the white hoist triangle and red star with blue and green-ish fields (rendered as light blue and green in most depictions).',
    },
    {
      id: 'flag-trivia-10',
      promptType: 'text',
      promptText: 'Which country’s flag has green, yellow, and red horizontal bands plus a blue disc with a yellow pentagram at center?',
      answer: 'Ethiopia',
      explanation: 'Ethiopia’s central emblem appears on the modern state flag variant.',
    },
  ],
}
