export default {
  id: 'flags-by-image',
  name: 'Flags by Image',
  type: 'custom-buzz',
  intro: 'A flag appears on screen. Buzz with the country name.',
  rules: [
    'Identify the country from the flag image',
    'Buzz in with the country name',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: [
    { label: 'Correct answer', points: 3, phase: 'normal' },
    { label: 'Wrong answer', points: -1, phase: 'normal' },
    { label: 'Correct steal', points: 2, phase: 'steal' },
    { label: 'Wrong steal', points: 0, phase: 'steal' },
  ],
  questions: [
    {
      id: 'flag-img-01',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/km.png',
      answer: 'Comoros',
      explanation: 'Comoros has a green hoist triangle with a crescent and stars plus four horizontal stripes.',
    },
    {
      id: 'flag-img-02',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/sc.png',
      answer: 'Seychelles',
      explanation: 'Seychelles has diagonal rays of blue, yellow, red, white, and green.',
    },
    {
      id: 'flag-img-03',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/er.png',
      answer: 'Eritrea',
      explanation: 'Eritrea has a red triangle with green/blue fields and a gold olive branch emblem.',
    },
    {
      id: 'flag-img-04',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/cf.png',
      answer: 'Central African Republic',
      explanation: 'CAR combines horizontal tricolor bands with a vertical red stripe and yellow star.',
    },
    {
      id: 'flag-img-05',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/st.png',
      answer: 'Sao Tome and Principe',
      explanation: 'Sao Tome and Principe has green-yellow-green stripes with a red triangle and two black stars.',
    },
    {
      id: 'flag-img-06',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/gq.png',
      answer: 'Equatorial Guinea',
      explanation: 'Equatorial Guinea has a blue hoist triangle and a central coat of arms.',
    },
    {
      id: 'flag-img-07',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/dj.png',
      answer: 'Djibouti',
      explanation: 'Djibouti has light blue and light green bands with a white triangle and red star.',
    },
    {
      id: 'flag-img-08',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/ss.png',
      answer: 'South Sudan',
      explanation: 'South Sudan has black-red-green stripes with white fimbriations and a blue triangle with a gold star.',
    },
    {
      id: 'flag-img-09',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/sz.png',
      answer: 'Eswatini',
      explanation: 'Eswatini features a Nguni shield and spears over a red central band.',
    },
    {
      id: 'flag-img-10',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/cv.png',
      answer: 'Cape Verde',
      explanation: 'Cape Verde has blue-white-red-white-blue stripes with ten yellow stars in a circle.',
    },
  ],
}
