export default {
  id: 'guess-the-song',
  name: 'Guess the Song',
  type: 'video',
  intro: 'Hear a short clip and identify the track. Give the song title first, then artist if you can.',
  rules: [
    'Buzz in once you know the song',
    'Song title is the main answer (+3)',
    'Artist name is a bonus (+1)',
    'Wrong answer is -1',
    'After a wrong answer, a steal is available (+2 for correct steal, 0 for wrong steal)',
  ],
  scoring: [
    { label: 'Correct song', points: 3 },
    { label: 'Correct artist', points: 1 },
    { label: 'Wrong answer', points: -1 },
    { label: 'Correct steal', points: 2 },
    { label: 'Wrong steal', points: 0 },
  ],
  questions: [
    {
      id: 'gts-last-last',
      video: 'https://www.youtube.com/embed/421w1j87fEM?start=38',
      answer: 'Burna Boy - Last Last',
      explanation: 'Released in 2022, "Last Last" became one of Burna Boy\'s biggest global crossover records.',
    },
    {
      id: 'gts-water',
      video: 'https://www.youtube.com/embed/XoiOOiuH8iI?start=35',
      answer: 'Tyla - Water',
      explanation: '"Water" helped push amapiano-influenced pop into mainstream global playlists in 2023.',
    },
    {
      id: 'gts-essence',
      video: 'https://www.youtube.com/embed/m77FDcKg96Q?start=42',
      answer: 'Wizkid ft. Tems - Essence',
      explanation: '"Essence" became a defining Afrobeats hit and charted internationally after its remix run.',
    },
    {
      id: 'gts-calm-down',
      video: 'https://www.youtube.com/embed/WcIcVapfqXw?start=32',
      answer: 'Rema - Calm Down',
      explanation: '"Calm Down" had one of the longest global chart runs for an Afrobeats song.',
    },
    {
      id: 'gts-love-nwantiti',
      video: 'https://www.youtube.com/embed/UGgqH_rXTTA?start=27',
      answer: 'CKay - Love Nwantiti',
      explanation: '"Love Nwantiti" exploded via short-form video apps before crossing into global radio.',
    },
    {
      id: 'gts-johnny',
      video: 'https://www.youtube.com/embed/C_XkTKoDI18?start=34',
      answer: 'Yemi Alade - Johnny',
      explanation: '"Johnny" is one of the most recognizable pan-African pop anthems of the 2010s.',
    },
    {
      id: 'gts-fall',
      video: 'https://www.youtube.com/embed/3Iyuym-Gci0?start=30',
      answer: 'Davido - Fall',
      explanation: '"Fall" was an early signal of Afrobeats\' sustained growth in US and UK markets.',
    },
    {
      id: 'gts-kante',
      video: 'https://www.youtube.com/embed/3bFPDfWReN0?start=36',
      answer: 'Davido ft. Fave - Kante',
      explanation: '"Kante" blends Afrobeats and RnB textures and became a fan favorite from Davido\'s 2023 album.',
    },
    {
      id: 'gts-peru',
      video: 'https://www.youtube.com/embed/pekzpzNCNDQ?start=14',
      answer: 'Fireboy DML ft. Ed Sheeran - Peru',
      explanation: 'The Ed Sheeran remix turned "Peru" into a global crossover smash, reaching top 10 in multiple countries.',
    },
    {
      id: 'gts-rush',
      video: 'https://www.youtube.com/embed/crtQSTYWtqE?start=20',
      answer: 'Ayra Starr - Rush',
      explanation: '"Rush" became a viral sensation in 2022 and established Ayra Starr as one of Afrobeats\' leading voices.',
    },
    {
      id: 'gts-kulosa',
      video: 'https://www.youtube.com/embed/R4qud199tQk?start=18',
      answer: 'Oxlade - KU LO SA',
      explanation: '"KU LO SA" went viral globally before a Camila Cabello remix expanded its reach even further.',
    },
    {
      id: 'gts-buga',
      video: 'https://www.youtube.com/embed/bLF90M96m2Q?start=22',
      answer: 'Kizz Daniel ft. Tekno - Buga',
      explanation: '"Buga" became a massive pan-African anthem in 2022, with its dance challenge spreading worldwide.',
    },
    {
      id: 'gts-soweto',
      video: 'https://www.youtube.com/embed/DPBRGWUgQsA?start=16',
      answer: 'Victony - Soweto',
      explanation: '"Soweto" grew from an underground Nigerian hit into a global Afrobeats staple via short-form video.',
    },
    {
      id: 'gts-soso',
      video: 'https://www.youtube.com/embed/k6eE3c70hgg?start=25',
      answer: 'Omah Lay - soso',
      explanation: '"soso" showcased Omah Lay\'s emotive Afro-fusion sound and became one of 2022\'s most-streamed African tracks.',
    },
    {
      id: 'gts-leg-over',
      video: 'https://www.youtube.com/embed/v15sS1sL_S4?start=20',
      answer: 'Mr Eazi - Leg Over',
      explanation: '"Leg Over" helped establish Mr Eazi\'s signature blend of Nigerian and Ghanaian sounds on the international stage.',
    },
    {
      id: 'gts-lonely-at-the-top',
      video: 'https://www.youtube.com/embed/bbVZo4Yw7pI?start=18',
      answer: 'Asake - Lonely At The Top',
      explanation: '"Lonely At The Top" cemented Asake\'s Amapiano-influenced Afrobeats style and his rise to headliner status.',
    },
    {
      id: 'gts-dior',
      video: 'https://www.youtube.com/embed/Soyd_3fTEbE?start=15',
      answer: 'Ruger - Dior',
      explanation: '"Dior" was a standout track from Ruger\'s debut EP and introduced his confident, stripped-back Afropop sound.',
    },
    {
      id: 'gts-pana',
      video: 'https://www.youtube.com/embed/8YhAFBOSk1U?start=20',
      answer: 'Tekno - Pana',
      explanation: '"Pana" became a defining Afrobeats slow jam of 2016 and remains one of Tekno\'s signature tracks.',
    },
    {
      id: 'gts-alcohol',
      video: 'https://www.youtube.com/embed/UEcAPvoSe_8?start=22',
      answer: 'Joeboy - Sip (Alcohol)',
      explanation: '"Sip (Alcohol)" highlighted Joeboy\'s smooth Afro-soul delivery and became a fan favorite in 2021.',
    },
    {
      id: 'gts-jeje',
      video: 'https://www.youtube.com/embed/g5rFro4XdZ0?start=22',
      answer: 'Diamond Platnumz - Jeje',
      explanation: '"Jeje" is one of Diamond Platnumz\'s biggest bongo flava hits, showcasing the Tanzania-born genre that fuses R&B with local rhythms.',
    },
    {
      id: 'gts-extravaganza',
      video: 'https://www.youtube.com/embed/SN0pDMTdmvw?start=20',
      answer: 'Sauti Sol - Extravaganza',
      explanation: '"Extravaganza" is a Kenyan afropop anthem from Sauti Sol, one of East Africa\'s most celebrated groups.',
    },
    {
      id: 'gts-kwa-ngwaru',
      video: 'https://www.youtube.com/embed/9MIhSSYuW8Y?start=25',
      answer: 'Harmonize ft. Diamond Platnumz - Kwa Ngwaru',
      explanation: '"Kwa Ngwaru" became one of the defining bongo flava collaborations of 2018, pairing two of Tanzania\'s biggest stars.',
    },
    {
      id: 'gts-bloque',
      video: 'https://www.youtube.com/embed/m32tFAo-M_g?start=28',
      answer: 'Fally Ipupa - Bloqué',
      explanation: '"Bloqué" is one of Fally Ipupa\'s signature tracks, blending Congolese rumba roots with modern Afropop production.',
    },
    {
      id: 'gts-yo-pe',
      video: 'https://www.youtube.com/embed/uJpjHW07mwE?start=20',
      answer: "Innoss'B - Yo Pe",
      explanation: '"Yo Pe" brought Innoss\'B — a young DRC star — to pan-African attention and spawned countless covers and dance videos.',
    },
    {
      id: 'gts-10-missed-calls',
      video: 'https://www.youtube.com/embed/_hhi1rKhVi0?start=15',
      answer: 'Black Coffee ft. Pharrell Williams & Jozzy - 10 Missed Calls',
      explanation: '"10 Missed Calls" cemented Black Coffee\'s status as one of South Africa\'s premier global DJ exports, pairing him with Pharrell Williams.',
    },
    {
      id: 'gts-lm3allem',
      video: 'https://www.youtube.com/embed/_Fwf45pIAtM?start=25',
      answer: 'Saad Lamjarred - LM3ALLEM',
      explanation: '"LM3ALLEM" became one of the most-viewed Arabic music videos ever and introduced Moroccan pop to a global audience.',
    },
    {
      id: 'gts-nour-el-ein',
      video: 'https://www.youtube.com/embed/KLJA-srM_yM?start=18',
      answer: 'Amr Diab - Nour El Ein',
      explanation: '"Nour El Ein" is one of the best-selling Middle Eastern and North African singles ever, making Amr Diab a household name internationally.',
    },
    {
      id: 'gts-jerusalema',
      video: 'https://www.youtube.com/embed/fCZVL_8D048?start=22',
      answer: 'Master KG ft. Nomcebo - Jerusalema',
      explanation: '"Jerusalema" became a global phenomenon in 2020, with the dance challenge spreading from South Africa to every continent.',
    },
    {
      id: 'gts-ke-star',
      video: 'https://www.youtube.com/embed/a9_da2P5JjQ?start=20',
      answer: 'Focalistic ft. Vigro Deep - Ke Star',
      explanation: '"Ke Star" is a defining Amapiano anthem from South Africa, helping cement the genre\'s dominance in African music.',
    },
    {
      id: 'gts-cinema',
      video: 'https://www.youtube.com/embed/AmXTw4z3FvU?start=24',
      answer: 'Fally Ipupa - Cinema',
      explanation: '"Cinema" is one of Fally Ipupa\'s most celebrated tracks, blending Congolese rumba with contemporary Afropop.',
    },
    {
      id: 'gts-bella-gims',
      video: 'https://www.youtube.com/embed/rMltoD1jCGI?start=20',
      answer: 'Maître Gims - Bella',
      explanation: '"Bella" was a massive hit for Maître Gims, the DRC-born French rap star, reaching number one in France and charting across Francophone Africa.',
    },
    {
      id: 'gts-jealousy',
      video: 'https://www.youtube.com/embed/7EgcG5Jy_yI?start=20',
      answer: 'Khalil Harrison & Tyler ICU ft. Leemckrazy & Ceeka RSA - Jealousy',
      explanation: '"Jealousy" is a sleek Amapiano anthem that showcases South Africa\'s dominance in contemporary African dance music.',
    },
  ],
}
