export default {
  label: 'Round 2',
  name: 'Guess the Language',
  type: 'video',
  intro: 'Watch a comedic video in a language, register, or slang variety from African and diasporic communities. Identify what you hear.',
  rules: [
    'Give the language or country',
    'No word-for-word translation needed — capturing the vibe counts',
    'Buzz in to answer — correct language: +3 pts, correct country: +1 pt, wrong answer: −1 pt',
    'A steal is always available after any answer — +2 correct, no penalty for wrong steal. You can only steal with a language guess.',
    'Host reveals the answer with a short explanation',
  ],
  scoring: [
    { label: 'Correct language', points: 3 },
    { label: 'Correct country',  points: 1 },
    { label: 'Wrong answer',  points: -1 },
    { label: 'Correct steal',    points: 2 },
    { label: 'Wrong steal',      points: 0 },
  ],
  questions: [
    {
      id: 'gtl-yoruba',
      video: 'https://www.youtube.com/watch?v=Av2Ax3E9aUY&list=PL9fybogIhpBtW3QaWb1pVWJvq990xrVEP&start=60',
      answer: 'Yoruba',
      countries: ['Nigeria', 'Benin', 'Togo'],
      explanation: 'Yoruba is one of Nigeria\'s major languages, spoken mainly in southwestern Nigeria and also in parts of Benin and Togo. It has a rich oral literary tradition and a strong diasporic influence in the Americas, especially through religious and cultural traditions like Brazilian Candomblé and Cuban Lucumí.',
    },
    {
      id: 'gtl-swahili',
      video: 'https://www.youtube.com/watch?v=ZzHb2zJcP-Q',
      answer: 'Swahili',
      countries: ['Tanzania', 'Kenya', 'Uganda', 'DRC', 'Rwanda'],
      explanation: 'Swahili (Kiswahili) is one of East Africa\'s great lingua francas, spoken widely across the region by both native and second-language speakers. It is an official language in countries including Kenya, Tanzania, Uganda, Rwanda, and the Democratic Republic of the Congo, and it has many Arabic loanwords due to centuries of Indian Ocean trade.',
    },
    {
      id: 'gtl-krio',
      video: 'https://www.youtube.com/watch?v=d83HnlEWsCQ&start=65',
      answer: 'Krio',
      countries: ['Sierra Leone'],
      explanation: 'Krio is an English-based creole and the main lingua franca of Sierra Leone. It developed from the language of freed slaves who settled in Freetown in the late 18th and early 19th centuries.',
    },
    {
      id: 'gtl-dinka',
      video: 'https://www.youtube.com/watch?v=zkRwVjQ3jkc&start=74',
      answer: 'Dinka',
      countries: ['South Sudan'],
      explanation: 'Dinka is a Nilotic language of South Sudan, spoken by the Dinka people — the country\'s largest ethnic group. It has a complex tonal system and is one of the most widely spoken languages in South Sudan.',
    },
    {
      id: 'gtl-lingala',
      video: 'https://www.youtube.com/watch?v=TzwyFfbxt5Q',
      answer: 'Lingala',
      countries: ['DRC', 'Republic of Congo', 'Central African Republic', 'Angola'],
      explanation: 'Lingala is a Bantu language spoken across the DRC, Republic of Congo, Central African Republic, and Angola. It\'s the language of Congolese rumba and ndombolo music, and one of the DRC\'s four national languages.',
    },
    {
      id: 'gtl-twi',
      video: 'https://www.youtube.com/watch?v=aBibVNmgpsM',
      answer: 'Twi',
      countries: ['Ghana'],
      explanation: 'Twi is widely spoken in Ghana and usually refers to the Asante and Akuapem varieties within the broader Akan language group. It is especially prominent in southern and central Ghana, including the Ashanti region.',
    },
    {
      id: 'gtl-amharic',
      video: 'https://www.youtube.com/watch?v=lap6CHT_5Us',
      answer: 'Amharic',
      countries: ['Ethiopia'],
      explanation: 'Amharic is one of Ethiopia\'s main languages and serves as the federal working language. It is a Semitic language written in the Ge\'ez (Ethiopic) script and is one of the most widely spoken Semitic languages in the world.',
    },
    {
      id: 'gtl-zulu',
      video: 'https://www.youtube.com/watch?v=9cR4sHsrdRo&start=60',
      answer: 'Zulu',
      countries: ['South Africa'],
      explanation: 'IsiZulu is South Africa\'s most widely spoken home language. It is a Bantu language known for its distinctive click consonants, which it shares with other Nguni languages such as Xhosa.',
    },
    {
      id: 'gtl-wolof',
      video: 'https://www.youtube.com/watch?v=dvL68Ebk-a8',
      answer: 'Wolof',
      countries: ['Senegal', 'Gambia', 'Mauritania'],
      explanation: 'Wolof is the dominant everyday language of Senegal and the Gambia, spoken natively by ~5 million and as a second language by ~12 million more — even though French is Senegal\'s official language. Central to Senegalese identity, music, and humor.',
    },
    {
      id: 'gtl-igbo',
      video: 'https://www.youtube.com/watch?v=M3LgkrR6qs8&start=675',
      answer: 'Igbo',
      countries: ['Nigeria'],
      explanation: 'Igbo is one of Nigeria\'s major languages, spoken primarily in the southeast. It is a tonal language with many regional dialects and is an important part of the cultural identity of the Igbo people.',
    },
    {
      id: 'gtl-somali',
      video: 'https://www.youtube.com/watch?v=Ma8qEuLp4Ek&start=25',
      answer: 'Somali',
      countries: ['Somalia', 'Ethiopia', 'Djibouti', 'Kenya'],
      explanation: 'Somali is a Cushitic (Afroasiatic) language spoken by ~22 million people across Somalia, Ethiopia, Djibouti, and Kenya. It\'s the most widely spoken Cushitic language and has a rich oral poetry tradition.',
    },
    {
      id: 'gtl-luganda',
      video: 'https://www.youtube.com/watch?v=2Ma52V_50jc',
      answer: 'Luganda',
      countries: ['Uganda'],
      explanation: 'Luganda is a Bantu language spoken by the Baganda — Uganda\'s largest ethnic group — and is the most widely spoken local language in the country. It\'s the official language of the historic Buganda Kingdom.',
    },
    {
      id: 'gtl-ewe',
      video: 'https://www.youtube.com/watch?v=IZf-zpfbb70',
      answer: 'Ewe',
      countries: ['Ghana', 'Togo', 'Benin'],
      explanation: 'Ewe is a Gbe language spoken across Ghana, Togo, and Benin by several million people. It belongs to the Volta-Congo language family and is especially prominent in southeastern Ghana and southern Togo.',
    },
    {
      id: 'gtl-tshiluba',
      video: 'https://www.youtube.com/watch?v=sNsaPbhj9sg&start=180',
      answer: 'Tshiluba',
      countries: ['DRC'],
      explanation: 'Tshiluba (Luba-Kasai) is a Bantu language of the Kasai region of the DRC, with about 6 million native speakers. One of the four national languages of the DRC alongside Lingala, Swahili, and Kikongo.',
    },
    {
      id: 'gtl-bambara',
      video: 'https://www.youtube.com/watch?v=pQfYmkWMDAw&start=810',
      answer: 'Bambara',
      countries: ['Mali', 'Burkina Faso', 'Guinea'],
      explanation: 'Bambara (Bamanankan) is a major Mande language and an important lingua franca of Mali. It is closely related to Dyula/Jula and other Manding varieties spoken across West Africa.',
    },
    {
      id: 'gtl-shona',
      video: 'https://www.youtube.com/watch?v=4VSu9bcvYOg&start=154',
      answer: 'Shona',
      countries: ['Zimbabwe', 'Mozambique'],
      explanation: 'Shona is Zimbabwe\'s most widely spoken indigenous language, used by about 75% of the population. A Bantu language with dialects including Karanga, Zezuru, and Korekore. Also spoken in parts of Mozambique.',
    },
    {
      id: 'gtl-tswana',
      video: 'https://www.youtube.com/watch?v=_Dh3JICHRGA&start=21',
      answer: 'Tswana',
      countries: ['Botswana', 'South Africa'],
      explanation: 'Setswana is a Bantu language and the national language of Botswana, also widely spoken in South Africa. About 5 million speakers. Closely related to Sesotho and Sepedi — together these are called the Sotho-Tswana languages.',
    },
    // {
    //   id: 'gtl-ibibio',
    //   video: 'Ibibio.mp4',
    //   answer: 'Ibibio',
    //   countries: ['Nigeria'],
    //   explanation: 'Ibibio is spoken by the Ibibio people of southeastern Nigeria, primarily in Akwa Ibom State. About 4 million speakers. It\'s closely related to Efik and part of the Cross River language group.',
    // },
    // {
    //   id: 'gtl-kikuyu',
    //   video: 'Kikuyu.mp4',
    //   answer: 'Kikuyu',
    //   countries: ['Kenya'],
    //   explanation: 'Kikuyu (Gikuyu) is a Bantu language spoken by Kenya\'s largest ethnic group, the Kikuyu, primarily around Mount Kenya. About 8 million speakers. Closely related to Meru and Embu.',
    // },
    {
      id: 'gtl-meru',
      video: 'https://www.youtube.com/watch?v=0S0Bl5o99ng&start=128',
      answer: 'Meru',
      countries: ['Kenya'],
      explanation: 'Kimeru is a Bantu language spoken by the Meru people of central Kenya, on the eastern slopes of Mount Kenya. About 2 million speakers. Closely related to Kikuyu and Embu, but distinct enough to be its own language.',
    },
    {
      id: 'gtl-tamazight',
      video: 'https://www.youtube.com/watch?v=J86rz3u5y4o',
      answer: 'Tamazight',
      countries: ['Morocco', 'Algeria', 'Libya', 'Tunisia', 'Mali', 'Niger'],
      explanation: 'Tamazight (Amazigh) is a family of Berber languages indigenous to North Africa, predating the Arab conquests by thousands of years. Spoken by tens of millions across Morocco, Algeria, and the broader Sahara region. Tifinagh, its ancient script, was recently revived and is now used in official contexts in Morocco.',
    },
    {
      id: 'gtl-ga',
      video: 'https://www.youtube.com/watch?v=WsHEQnSMmT4',
      answer: 'Ga',
      countries: ['Ghana'],
      explanation: 'Ga is a Kwa language spoken primarily in the Greater Accra region of Ghana, especially in and around the capital. About 745,000 native speakers. It\'s the home language of the Ga people and distinct from the Akan languages like Twi that dominate much of southern Ghana.',
    },
    {
      id: 'gtl-kinyarwanda',
      video: 'https://www.youtube.com/watch?v=9pJ8-XS78j8',
      answer: 'Kinyarwanda',
      countries: ['Rwanda', 'Uganda', 'DRC'],
      explanation: 'Kinyarwanda is the national language of Rwanda, spoken by virtually the entire population — one of the rare African countries where a single indigenous language unites the nation. A Bantu language closely related to Kirundi (Burundi).',
    },
    {
      id: 'gtl-malagasy',
      video: 'https://www.youtube.com/watch?v=SowWvjh6Ef8',
      answer: 'Malagasy',
      countries: ['Madagascar'],
      explanation: 'Malagasy is the national language of Madagascar and one of Africa\'s most surprising linguistic outliers — it belongs to the Austronesian family, making it more closely related to languages in Borneo and the Philippines than to any African language. This reflects Madagascar\'s settlement by seafarers from Southeast Asia around 1,500 years ago, long before significant African contact.',
    },
    {
      id: 'gtl-maasai',
      video: 'https://www.youtube.com/watch?v=3SFHx-tLCUk&start=1',
      answer: 'Maa',
      countries: ['Kenya', 'Tanzania'],
      explanation: 'Maa (often called Maasai) is a Nilotic language spoken by the Maasai and Samburu peoples of Kenya and Tanzania. Unlike most languages in the region, Maa is not Bantu — it belongs to the Nilo-Saharan family. The Maasai are one of the most recognizable cultures in Africa, known for their distinctive red shukas, beadwork, and semi-nomadic pastoralist lifestyle.',
    },
    {
      id: 'gtl-fula',
      video: 'https://www.youtube.com/watch?v=EW-rU4Z0-GU',
      answer: 'Fula',
      countries: ['Guinea', 'Senegal', 'Mali', 'Niger', 'Nigeria', 'Cameroon', 'Sudan'],
      explanation: 'Fula (also called Fulani, Fulfulde, or Peul) is one of the most widely distributed languages in Africa, spoken by the Fula people across a vast belt from Senegal to Sudan — over 20 countries in total. About 40 million speakers. The Fula are historically known as cattle herders and Islamic scholars, and their language has no single dominant country of origin.',
    },
    {
      id: 'gtl-oromo',
      video: 'https://www.youtube.com/watch?v=fAgdocz4sIk&start=480',
      answer: 'Oromo',
      countries: ['Ethiopia', 'Kenya'],
      explanation: 'Oromo (Afaan Oromoo) is a Cushitic language and the most widely spoken language in Ethiopia, with over 40 million native speakers. The Oromo are Ethiopia\'s largest ethnic group. It was officially standardized and given equal status with Amharic in the late 20th century. Written in the Latin-based Qubee script.',
    },
    {
      id: 'gtl-hausa',
      video: 'https://www.youtube.com/watch?v=RjnpCaVX4TQ&start=11',
      answer: 'Hausa',
      countries: ['Nigeria', 'Niger', 'Ghana', 'Cameroon', 'Sudan'],
      explanation: 'Hausa is the most widely spoken language in West Africa by number of speakers — over 70 million native speakers and many more as a second language. An Afroasiatic language of northern Nigeria and Niger, it has long served as a major trade language across the Sahel. Hausa literature, music, and film (Kannywood) have a massive cultural footprint across the continent.',
    },
    {
      id: 'gtl-sango',
      video: 'https://www.youtube.com/watch?v=pyFoCSDm2qA&start=10',
      answer: 'Sango',
      countries: ['Central African Republic', 'DRC', 'Chad'],
      explanation: 'Sango is the national language of the Central African Republic and one of its two official languages alongside French. A Ngbandi-based creole with about 500,000 native speakers and over 5 million second-language speakers across the CAR, southern Chad, and northern DRC. It serves as the main lingua franca across the CAR\'s diverse linguistic landscape.',
    },
    {
      id: 'gtl-kituba',
      video: 'https://www.youtube.com/watch?v=thp6XPLa2qA&start=10',
      answer: 'Kituba',
      countries: ['DRC', 'Republic of Congo'],
      explanation: 'Kituba (also called Munukutuba or Kikongo ya Leta) is a Bantu-based creole that emerged as a trade and administrative language in the Congo River basin. It is one of the four national languages of the DRC alongside Lingala, Swahili, and Tshiluba, and is dominant in the western regions. It developed from Kikongo but is simplified enough to be a distinct language.',
    },
    {
      id: 'gtl-cameroonian-pidgin',
      video: 'https://www.youtube.com/watch?v=lozSaftH4jI&start=10',
      answer: 'Cameroonian Pidgin',
      countries: ['Cameroon'],
      explanation: 'Cameroonian Pidgin English is a creole and the most widely used lingua franca in Cameroon, spoken by millions across the Anglophone and beyond. It developed from contact between English traders and local populations and is distinct from Nigerian Pidgin — slower, with different vowel sounds and vocabulary.',
    },
    {
      id: 'gtl-xhosa',
      video: 'https://www.youtube.com/watch?v=bd7QuovP4Mo&start=134',
      answer: 'Xhosa',
      countries: ['South Africa'],
      explanation: 'IsiXhosa is one of South Africa\'s 11 official languages and the home language of Nelson Mandela and Miriam Makeba. It is famous for its distinctive click consonants — three types: dental (c), lateral (x), and palatal (q). About 8 million native speakers, mostly in the Eastern Cape.',
    },
    {
      id: 'gtl-chichewa',
      video: 'https://www.youtube.com/watch?v=g2L_YR5P5KE&start=60',
      answer: 'Chichewa',
      countries: ['Malawi', 'Zambia', 'Zimbabwe', 'Mozambique'],
      explanation: 'Chichewa (also called Nyanja) is the national language of Malawi and one of Zambia\'s major languages. A Bantu language spoken by about 12 million people across southeast Africa. In Malawi it serves as the primary lingua franca; in Zambia it\'s called Nyanja and is dominant in Lusaka.',
    },
    {
      id: 'gtl-afrikaans',
      video: 'https://www.youtube.com/watch?v=1HJJZL9PuI8&start=146',
      answer: 'Afrikaans',
      countries: ['South Africa', 'Namibia'],
      explanation: 'Afrikaans is a West Germanic language that evolved from Dutch in southern Africa. It is one of South Africa\'s 11 official languages and the primary language of Namibia after English. About 7 million native speakers — it sounds like a slower, simplified Dutch and is mutually intelligible with it to a degree.',
    },
    {
      id: 'gtl-egyptian-arabic',
      video: 'https://www.youtube.com/watch?v=wUO-RjBjYxU&start=210',
      answer: 'Egyptian Arabic',
      countries: ['Egypt'],
      explanation: 'Egyptian Arabic (Masri) is the most widely understood Arabic dialect in the world, largely because of Egypt\'s dominance in Arab film, TV, and music. Over 100 million speakers. It differs from Modern Standard Arabic and other dialects in pronunciation, vocabulary, and rhythm — famously melodic and expressive.',
    },
    {
      id: 'gtl-darija',
      video: 'https://www.youtube.com/watch?v=lVf_1LY_gj8&start=10',
      answer: 'Darija',
      countries: ['Morocco', 'Algeria', 'Tunisia'],
      explanation: 'Darija is the colloquial Arabic of North Africa\'s Maghreb region — distinct enough from Modern Standard Arabic that other Arab speakers often can\'t understand it. It mixes Arabic with Amazigh, French, and Spanish loanwords. About 40 million speakers, primarily in Morocco and Algeria.',
    },
    {
      id: 'gtl-itshekiri',
      video: 'https://www.youtube.com/watch?v=QGMwupjOwYI&start=120',
      answer: 'Itshekiri',
      countries: ['Nigeria'],
      explanation: 'Itshekiri (also written Itsekiri) is a language spoken in Nigeria\'s Niger Delta, especially in Delta State around Warri. It has strong historical contact with neighboring Edo and Yoruba-speaking communities through trade and migration.',
    },
    {
      id: 'gtl-urhobo',
      video: 'https://www.youtube.com/watch?v=XtaN4v5wPwo&start=134',
      answer: 'Urhobo',
      countries: ['Nigeria'],
      explanation: 'Urhobo is spoken by the Urhobo people of southern Nigeria, mainly in Delta State. It is part of the larger Niger-Congo family and is one of the key indigenous languages of the western Niger Delta.',
    },
    {
      id: 'gtl-efik-ibibio',
      video: 'https://www.youtube.com/watch?v=I57xP7MsOD0&start=39',
      answer: 'Efik / Ibibio',
      countries: ['Nigeria'],
      explanation: 'Efik and Ibibio are closely related Lower Cross languages spoken in southeastern Nigeria, especially in Akwa Ibom and Cross River states. They share substantial vocabulary and cultural overlap while remaining distinct varieties.',
    },
    {
      id: 'gtl-ijaw',
      video: 'https://www.youtube.com/watch?v=IF2OllCp-0o&start=7',
      answer: 'Ijaw',
      countries: ['Nigeria'],
      explanation: 'Ijaw refers to a cluster of related languages spoken by Ijaw communities across the Niger Delta in southern Nigeria. It is central to the linguistic and cultural identity of many riverine communities in Bayelsa, Delta, and Rivers states.',
    },
    {
      id: 'gtl-kpelle',
      video: 'https://www.youtube.com/watch?v=hBj6yg-fCgk',
      answer: 'Kpelle',
      countries: ['Liberia', 'Guinea'],
      explanation: 'Kpelle is a Mande language spoken mainly in central and northern Liberia and neighboring southeastern Guinea. It is one of Liberia\'s largest indigenous languages and a key part of Kpelle cultural identity.',
    },
    {
      id: 'gtl-koloqua',
      video: 'https://www.youtube.com/watch?v=3Y434an_HmY',
      answer: 'Koloqua',
      countries: ['Liberia'],
      explanation: 'Koloqua (also called Liberian Kolokwa) is an English-lexifier creole widely spoken in Liberia, especially in urban settings like Monrovia. It blends English vocabulary with local linguistic structures and is a major everyday lingua franca.',
    },
  ],
}
