export default {
  id: 'mix-and-match',
  name: 'Independence Celeb...',
  type: 'custom-buzz',
  intro: 'A curated selection of questions from across different rounds, featuring 15 featured African countries.',
  rules: [
    'Host reads or displays the question',
    'Teams buzz in with their answer',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: {
    correctPoints: 3,
    wrongPoints: -1,
    stealEnabled: true,
    correctStealPoints: 2,
    wrongStealPoints: 0,
  },
  questions: [
    // GAMBIA
    {
      id: 'mam-gambia-01',
      promptType: 'text',
      promptText: 'What is the capital city of The Gambia?',
      answer: 'Banjul',
      explanation: 'Banjul is on St. Mary\'s Island where the Gambia River meets the Atlantic.',
    },
    // EGYPT
    {
      id: 'mam-egypt-01',
      promptType: 'text',
      promptText: 'What is the capital city of Egypt?',
      answer: 'Cairo',
      explanation: 'Cairo is the largest city in Africa and the Arab world.',
    },
    {
      id: 'mam-egypt-02',
      promptType: 'text',
      promptText: 'Which river\'s annual flooding supported agriculture in ancient Egypt?',
      answer: 'Nile River',
      explanation: 'Ancient Egypt depended on the Nile\'s annual inundation to sustain its agricultural population.',
    },
    {
      id: 'mam-egypt-03',
      promptType: 'text',
      promptText: 'Was the Aswan High Dam in Egypt completed before or after the Six-Day War?',
      answer: 'After',
      explanation: 'The Six-Day War was fought in June 1967. Egypt\'s Aswan High Dam was completed in 1970.',
    },
    {
      id: 'mam-egypt-04',
      promptType: 'text',
      promptText: 'I was the first Arab writer to win the Nobel Prize in Literature, receiving it in 1988. My Cairo Trilogy chronicles three generations of a middle-class family in 20th-century Egypt. Who am I?',
      answer: 'Naguib Mahfouz',
      explanation: 'Naguib Mahfouz (1911–2006) wrote over 30 novels and 350 short stories. His Cairo Trilogy is considered one of the masterpieces of world literature.',
    },
    // MOROCCO
    {
      id: 'mam-morocco-01',
      promptType: 'text',
      promptText: 'What is the capital city of Morocco?',
      answer: 'Rabat',
      explanation: 'Rabat is the political capital; Casablanca is the larger economic hub.',
    },
    {
      id: 'mam-morocco-02',
      promptType: 'text',
      promptText: 'I border Morocco, Western Sahara, Mali, Niger, Libya, and Tunisia. Which country am I?',
      answer: 'Algeria',
      explanation: 'Algeria is Africa\'s largest country by area. Over 80% of its territory is covered by the Sahara Desert.',
    },
    // GHANA
    {
      id: 'mam-ghana-01',
      promptType: 'text',
      promptText: 'What is the capital city of Ghana?',
      answer: 'Accra',
      explanation: 'Accra is on the Gulf of Guinea and is one of the fastest-growing cities on the continent.',
    },
    {
      id: 'mam-ghana-02',
      promptType: 'text',
      promptText: 'In what year did Ghana (formerly the Gold Coast) gain independence from Great Britain?',
      answer: '1957',
      explanation: 'Ghana became independent on March 6, 1957, becoming the first sub-Saharan African country to gain independence in the colonial era.',
    },
    {
      id: 'mam-ghana-03',
      promptType: 'text',
      promptText: 'Did Ghana gain independence before or after Nigeria?',
      answer: 'Before',
      explanation: 'Ghana gained independence in March 1957; Nigeria followed in October 1960.',
    },
    {
      id: 'mam-ghana-04',
      promptType: 'text',
      promptText: 'Before independence, modern Ghana was known by what colonial name?',
      answer: 'Gold Coast',
      explanation: 'The British colony called the Gold Coast gained independence in 1957 and became Ghana.',
    },
    {
      id: 'mam-ghana-05',
      promptType: 'text',
      promptText: 'My most famous political motto was "Seek ye first the political kingdom." I was the first Prime Minister and later first President of Ghana. Who am I?',
      answer: 'Kwame Nkrumah',
      explanation: 'Kwame Nkrumah (1909–1972) led Ghana to independence in 1957 and became one of the founding fathers of Pan-Africanism.',
    },
    {
      id: 'mam-ghana-06',
      promptType: 'text',
      promptText: 'Did the first Pan-African Conference take place before or after Ghana gained independence?',
      answer: 'Before',
      explanation: 'The first Pan-African Conference was held in London in 1900. Both predate Ghana\'s independence in 1957.',
    },
    // MAURITIUS
    {
      id: 'mam-mauritius-01',
      promptType: 'text',
      promptText: 'What is the capital city of Mauritius?',
      answer: 'Port Louis',
      explanation: 'Port Louis is the financial center of Mauritius and one of Africa\'s wealthiest cities per capita.',
    },
    // TUNISIA
    {
      id: 'mam-tunisia-01',
      promptType: 'text',
      promptText: 'What is the capital city of Tunisia?',
      answer: 'Tunis',
      explanation: 'Tunis is adjacent to the ancient ruins of Carthage.',
    },
    {
      id: 'mam-tunisia-02',
      promptType: 'text',
      promptText: 'I border Tunisia, Algeria, Niger, Chad, Sudan, and Egypt. Which country am I?',
      answer: 'Libya',
      explanation: 'Libya is North Africa\'s largest country by area. It borders the Mediterranean Sea to the north.',
    },
    // NAMIBIA
    {
      id: 'mam-namibia-01',
      promptType: 'text',
      promptText: 'What is the capital city of Namibia?',
      answer: 'Windhoek',
      explanation: 'Windhoek is centrally located and was founded as a German colonial town.',
    },
    // SENEGAL
    {
      id: 'mam-senegal-01',
      promptType: 'text',
      promptText: 'What is the capital city of Senegal?',
      answer: 'Dakar',
      explanation: 'Dakar is the westernmost point of mainland Africa.',
    },
    // ZIMBABWE
    {
      id: 'mam-zimbabwe-01',
      promptType: 'text',
      promptText: 'What is the capital city of Zimbabwe?',
      answer: 'Harare',
      explanation: 'Harare was formerly called Salisbury during the colonial era.',
    },
    {
      id: 'mam-zimbabwe-02',
      promptType: 'text',
      promptText: 'Great Zimbabwe, the major stone-ruin city, is in which present-day country?',
      answer: 'Zimbabwe',
      explanation: 'Great Zimbabwe lies in southeastern Zimbabwe and was the center of a major trading power from the 11th to the 15th centuries.',
    },
    {
      id: 'mam-zimbabwe-03',
      promptType: 'text',
      promptText: 'I border Zambia, Mozambique, South Africa, and Botswana. Which country am I?',
      answer: 'Zimbabwe',
      explanation: 'Zimbabwe is landlocked in Southern Africa. Victoria Falls, one of the Seven Natural Wonders of the World, sits on its border with Zambia.',
    },
    {
      id: 'mam-zimbabwe-04',
      promptType: 'text',
      promptText: 'Did Zimbabwe gain independence before or after Mozambique?',
      answer: 'After',
      explanation: 'Mozambique gained independence from Portugal in June 1975. Zimbabwe gained independence from Britain in April 1980.',
    },
    // TOGO
    {
      id: 'mam-togo-01',
      promptType: 'text',
      promptText: 'What is the capital city of Togo?',
      answer: 'Lomé',
      explanation: 'Lomé is a major West African port city on the Gulf of Guinea.',
    },
    // SIERRA LEONE
    {
      id: 'mam-sierraleone-01',
      promptType: 'text',
      promptText: 'What is the capital city of Sierra Leone?',
      answer: 'Freetown',
      explanation: 'Freetown was founded in 1792 as a home for freed slaves.',
    },
    {
      id: 'mam-sierraleone-02',
      promptType: 'text',
      promptText: 'Did the Rwandan genocide happen before or after the start of the Sierra Leone Civil War?',
      answer: 'After',
      explanation: 'The Sierra Leone Civil War began in March 1991. The Rwandan genocide occurred in April–July 1994.',
    },
    // ERITREA
    {
      id: 'mam-eritrea-01',
      promptType: 'text',
      promptText: 'What is the capital city of Eritrea?',
      answer: 'Asmara',
      explanation: 'Asmara is known for its modernist architecture from the Italian colonial era.',
    },
    {
      id: 'mam-eritrea-02',
      promptType: 'text',
      promptText: 'My only neighbours are Sudan, Ethiopia, and Djibouti. Which country am I?',
      answer: 'Eritrea',
      explanation: 'Eritrea gained independence from Ethiopia in 1993 after a 30-year war. It borders the Red Sea to the east.',
    },
    // SOUTH AFRICA
    {
      id: 'mam-sa-01',
      promptType: 'text',
      promptText: 'What is the administrative capital of South Africa?',
      answer: 'Pretoria',
      explanation: 'South Africa has three capitals: Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial).',
    },
    {
      id: 'mam-sa-02',
      promptType: 'text',
      promptText: 'I spent 27 years in prison — first on Robben Island, then Pollsmoor, then Victor Verster. I became South Africa\'s first democratically elected president in 1994. Who am I?',
      answer: 'Nelson Mandela',
      explanation: 'Nelson Mandela (1918–2013) was imprisoned from 1964 to 1990 and served as South Africa\'s president from 1994 to 1999.',
    },
    {
      id: 'mam-sa-03',
      promptType: 'text',
      promptText: 'Was Nelson Mandela released from prison before or after South Africa held its first democratic election?',
      answer: 'Before',
      explanation: 'Mandela was released in February 1990. South Africa\'s first democratic election was in April 1994.',
    },
    {
      id: 'mam-sa-04',
      promptType: 'text',
      promptText: 'On what date was Nelson Mandela inaugurated as President of South Africa?',
      answer: 'May 10, 1994',
      explanation: 'Mandela was inaugurated on May 10, 1994, following South Africa\'s first democratic elections.',
    },
    {
      id: 'mam-sa-05',
      promptType: 'text',
      promptText: 'I was born near Johannesburg and was exiled from South Africa for approximately 30 years. I was the first African artist to win a Grammy Award, in 1965. I am nicknamed "Mama Africa". Who am I?',
      answer: 'Miriam Makeba',
      explanation: 'Miriam Makeba (1932–2008) was a South African singer and activist whose music helped put African sound on the global stage.',
    },
    {
      id: 'mam-sa-06',
      promptType: 'text',
      promptText: 'Did apartheid officially begin in South Africa before or after the Sharpeville massacre?',
      answer: 'Before',
      explanation: 'Apartheid was officially instituted in 1948. The Sharpeville massacre occurred in March 1960.',
    },
    {
      id: 'mam-sa-07',
      promptType: 'text',
      promptText: 'Did Wangari Maathai win the Nobel Peace Prize before or after South Africa hosted the FIFA World Cup?',
      answer: 'Before',
      explanation: 'Wangari Maathai won the Nobel Peace Prize in 2004. South Africa hosted the 2010 FIFA World Cup.',
    },
    {
      id: 'mam-sa-08',
      promptType: 'text',
      promptText: 'I am entirely surrounded by South Africa on all sides. Which country am I?',
      answer: 'Lesotho',
      explanation: 'Lesotho is an enclave state completely surrounded by South Africa — one of only three countries in the world that are entirely within another country.',
    },
    // ETHIOPIA
    {
      id: 'mam-ethiopia-01',
      promptType: 'text',
      promptText: 'What is the capital city of Ethiopia?',
      answer: 'Addis Ababa',
      explanation: 'Addis Ababa means "new flower" in Amharic and is also the headquarters of the African Union.',
    },
    {
      id: 'mam-ethiopia-02',
      promptType: 'text',
      promptText: 'Which Ethiopian emperor led the forces that defeated Italy at the Battle of Adwa in 1896?',
      answer: 'Menelik II',
      explanation: 'At Adwa on March 1, 1896, Emperor Menelik II led Ethiopia to victory over Italy.',
    },
    {
      id: 'mam-ethiopia-03',
      promptType: 'text',
      promptText: 'I ruled my country for over 40 years and was considered divine by a religious movement originating in Jamaica. I was the last emperor of Ethiopia. Who am I?',
      answer: 'Haile Selassie',
      explanation: 'Haile Selassie (1892–1975) ruled Ethiopia from 1930 until 1974. He is revered as a messianic figure in Rastafari.',
    },
    {
      id: 'mam-ethiopia-04',
      promptType: 'text',
      promptText: 'I border Eritrea, Djibouti, Somalia, Kenya, South Sudan, and Sudan. Which country am I?',
      answer: 'Ethiopia',
      explanation: 'Ethiopia is Africa\'s second most populous country and the only African nation never colonised by a European power.',
    },
    {
      id: 'mam-senegal-02',
      promptType: 'text',
      promptText: 'In what year did Senegal gain independence from France?',
      answer: '1960',
      explanation: 'Senegal gained independence on April 4, 1960, and is known as one of Africa\'s most stable democracies.',
    },
    {
      id: 'mam-togo-02',
      promptType: 'text',
      promptText: 'Togo gained independence from which European nation in 1960?',
      answer: 'France',
      explanation: 'Togo, formerly French Togoland, became independent on April 27, 1960.',
    },
    {
      id: 'mam-mauritius-02',
      promptType: 'text',
      promptText: 'Mauritius, an island nation, gained independence from which country in 1968?',
      answer: 'United Kingdom',
      explanation: 'Mauritius became independent on March 12, 1968, and is known as a multicultural success story and economic powerhouse.',
    },
  ],
}
