export default {
  id: 'mix-and-match',
  name: 'Africa Trivia',
  type: 'custom-buzz',
  intro: 'A curated selection of questions from across different rounds, featuring 15 featured African countries.',
  rules: [
    'Host reads or displays the question',
    'Teams buzz in with their answer',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: {
    correctPoints: 3,
    wrongPoints: -1,
    stealEnabled: true,
    correctStealPoints: 2,
    wrongStealPoints: 0,
  },
  questions: [
    {
      id: 'mam-sa-02',
      promptType: 'text',
      promptText: 'I spent 27 years in prison — first on Robben Island, then Pollsmoor, then Victor Verster. I became South Africa\'s first democratically elected president in 1994. Who am I?',
      answer: 'Nelson Mandela',
      explanation: 'Nelson Mandela (1918–2013) was imprisoned from 1964 to 1990 and served as South Africa\'s president from 1994 to 1999.',
    },
    {
      id: 'mam-egypt-04',
      promptType: 'text',
      promptText: 'I was the first Arab writer to win the Nobel Prize in Literature, receiving it in 1988. My Cairo Trilogy chronicles three generations of a middle-class family in 20th-century Egypt. Who am I?',
      answer: 'Naguib Mahfouz',
      explanation: 'Naguib Mahfouz (1911–2006) wrote over 30 novels and 350 short stories. His Cairo Trilogy is considered one of the masterpieces of world literature.',
    },
    {
      id: 'mam-gambia-01',
      promptType: 'text',
      promptText: 'What is the capital city of The Gambia?',
      answer: 'Banjul',
      explanation: 'Banjul is on St. Mary\'s Island where the Gambia River meets the Atlantic.',
    },
    {
      id: 'mam-zimbabwe-03',
      promptType: 'text',
      promptText: 'I border Zambia, Mozambique, South Africa, and Botswana. Which country am I?',
      answer: 'Zimbabwe',
      explanation: 'Zimbabwe is landlocked in Southern Africa. Victoria Falls, one of the Seven Natural Wonders of the World, sits on its border with Zambia.',
    },
    {
      id: 'mam-togo-02',
      promptType: 'text',
      promptText: 'Togo gained independence from which European nation in 1960?',
      answer: 'France',
      explanation: 'Togo, formerly French Togoland, became independent on April 27, 1960.',
    },
    {
      id: 'mam-ghana-05',
      promptType: 'text',
      promptText: 'My most famous political motto was "Seek ye first the political kingdom." I was the first Prime Minister and later first President of Ghana. Who am I?',
      answer: 'Kwame Nkrumah',
      explanation: 'Kwame Nkrumah (1909–1972) led Ghana to independence in 1957 and became one of the founding fathers of Pan-Africanism.',
    },
    {
      id: 'mam-eritrea-01',
      promptType: 'text',
      promptText: 'What is the capital city of Eritrea?',
      answer: 'Asmara',
      explanation: 'Asmara is known for its modernist architecture from the Italian colonial era.',
    },

    {
      id: 'mam-sa-07',
      promptType: 'text',
      promptText: 'Did Wangari Maathai win the Nobel Peace Prize before or after South Africa hosted the FIFA World Cup?',
      answer: 'Before',
      explanation: 'Wangari Maathai won the Nobel Peace Prize in 2004. South Africa hosted the 2010 FIFA World Cup.',
    },
    {
      id: 'mam-sierraleone-02',
      promptType: 'text',
      promptText: 'Did the Rwandan genocide happen before or after the start of the Sierra Leone Civil War?',
      answer: 'After',
      explanation: 'The Sierra Leone Civil War began in March 1991. The Rwandan genocide occurred in April–July 1994.',
    },
    {
      id: 'mam-egypt-03',
      promptType: 'text',
      promptText: 'Was the Aswan High Dam in Egypt completed before or after the Six-Day War?',
      answer: 'After',
      explanation: 'The Six-Day War was fought in June 1967. Egypt\'s Aswan High Dam was completed in 1970.',
    },
    {
      id: 'mam-sa-03',
      promptType: 'text',
      promptText: 'Was Nelson Mandela released from prison before or after South Africa held its first democratic election?',
      answer: 'Before',
      explanation: 'Mandela was released in February 1990. South Africa\'s first democratic election was in April 1994.',
    },


    {
      id: 'mam-ethiopia-02',
      promptType: 'text',
      promptText: 'Which Ethiopian emperor led the forces that defeated Italy at the Battle of Adwa in 1896?',
      answer: 'Menelik II',
      explanation: 'At Adwa on March 1, 1896, Emperor Menelik II led Ethiopia to victory over Italy.',
    },
    {
      id: 'mam-ethiopia-04',
      promptType: 'text',
      promptText: 'I border Eritrea, Djibouti, Somalia, Kenya, South Sudan, and Sudan. Which country am I?',
      answer: 'Ethiopia',
      explanation: 'Ethiopia is Africa\'s second most populous country and the only African nation never colonised by a European power.',
    },
    {
      id: 'mam-sa-01',
      promptType: 'text',
      promptText: 'What is the administrative capital of South Africa?',
      answer: 'Pretoria',
      explanation: 'South Africa has three capitals: Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial).',
    },
    {
      id: 'mam-egypt-02',
      promptType: 'text',
      promptText: 'Which river\'s annual flooding supported agriculture in ancient Egypt?',
      answer: 'Nile River',
      explanation: 'Ancient Egypt depended on the Nile\'s annual inundation to sustain its agricultural population.',
    },

    {
      id: 'mam-ghana-01',
      promptType: 'text',
      promptText: 'What is the capital city of Ghana?',
      answer: 'Accra',
      explanation: 'Accra is on the Gulf of Guinea and is one of the fastest-growing cities on the continent.',
    },

    {
      id: 'mam-ethiopia-03',
      promptType: 'text',
      promptText: 'I ruled my country for over 40 years and was considered divine by a religious movement originating in Jamaica. I was the last emperor of Ethiopia. Who am I?',
      answer: 'Haile Selassie',
      explanation: 'Haile Selassie (1892–1975) ruled Ethiopia from 1930 until 1974. He is revered as a messianic figure in Rastafari.',
    },
    {
      id: 'mam-namibia-01',
      promptType: 'text',
      promptText: 'What is the capital city of Namibia?',
      answer: 'Windhoek',
      explanation: 'Windhoek is centrally located and was founded as a German colonial town.',
    },
    {
      id: 'mam-togo-01',
      promptType: 'text',
      promptText: 'What is the capital city of Togo?',
      answer: 'Lomé',
      explanation: 'Lomé is a major West African port city on the Gulf of Guinea.',
    },

    {
      id: 'mam-sierraleone-01',
      promptType: 'text',
      promptText: 'What is the capital city of Sierra Leone?',
      answer: 'Freetown',
      explanation: 'Freetown was founded in 1792 as a home for freed slaves.',
    },
    {
      id: 'mam-sa-04',
      promptType: 'text',
      promptText: 'On what date was Nelson Mandela inaugurated as President of South Africa?',
      answer: 'May 10, 1994',
      explanation: 'Mandela was inaugurated on May 10, 1994, following South Africa\'s first democratic elections.',
    },
    {
      id: 'mam-ghana-02',
      promptType: 'text',
      promptText: 'In what year did Ghana (formerly the Gold Coast) gain independence from Great Britain?',
      answer: '1957',
      explanation: 'Ghana became independent on March 6, 1957, becoming the first sub-Saharan African country to gain independence in the colonial era.',
    },
    {
      id: 'mam-tunisia-01',
      promptType: 'text',
      promptText: 'What is the capital city of Tunisia?',
      answer: 'Tunis',
      explanation: 'Tunis is adjacent to the ancient ruins of Carthage.',
    },
    {
      id: 'mam-zimbabwe-01',
      promptType: 'text',
      promptText: 'What is the capital city of Zimbabwe?',
      answer: 'Harare',
      explanation: 'Harare was formerly called Salisbury during the colonial era.',
    },


    {
      id: 'mam-mauritius-02',
      promptType: 'text',
      promptText: 'Mauritius, an island nation, gained independence from which country in 1968?',
      answer: 'United Kingdom',
      explanation: 'Mauritius became independent on March 12, 1968, and is known as a multicultural success story and economic powerhouse.',
    },

    {
      id: 'mam-egypt-01',
      promptType: 'text',
      promptText: 'What is the capital city of Egypt?',
      answer: 'Cairo',
      explanation: 'Cairo is the largest city in Africa and the Arab world.',
    },

    {
      id: 'mam-ghana-04',
      promptType: 'text',
      promptText: 'Before independence, modern Ghana was known by what colonial name?',
      answer: 'Gold Coast',
      explanation: 'The British colony called the Gold Coast gained independence in 1957 and became Ghana.',
    },
    {
      id: 'mam-senegal-02',
      promptType: 'text',
      promptText: 'In what year did Senegal gain independence from France?',
      answer: '1960',
      explanation: 'Senegal gained independence on April 4, 1960, and is known as one of Africa\'s most stable democracies.',
    },


    {
      id: 'mam-ethiopia-01',
      promptType: 'text',
      promptText: 'What is the capital city of Ethiopia?',
      answer: 'Addis Ababa',
      explanation: 'Addis Ababa means "new flower" in Amharic and is also the headquarters of the African Union.',
    },

    {
      id: 'mam-morocco-01',
      promptType: 'text',
      promptText: 'What is the capital city of Morocco?',
      answer: 'Rabat',
      explanation: 'Rabat is the political capital; Casablanca is the larger economic hub.',
    },
    {
      id: 'mam-sa-heart-transplant',
      promptType: 'text',
      promptText: 'Which South African medical pioneer performed the world\'s first successful heart transplant in 1967?',
      answer: 'Christiaan Barnard',
      explanation: 'Christiaan Barnard performed the first successful human heart transplant on December 3, 1967, at Groote Schuur Hospital in Cape Town, South Africa.',
    },
    {
      id: 'mam-flag-gambia',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/gm.png',
      answer: 'Gambia',
      explanation: 'National flag of Gambia.',
    },
    {
      id: 'mam-flag-egypt',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/eg.png',
      answer: 'Egypt',
      explanation: 'National flag of Egypt.',
    },
    {
      id: 'mam-flag-morocco',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/ma.png',
      answer: 'Morocco',
      explanation: 'National flag of Morocco.',
    },
    {
      id: 'mam-flag-ghana',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/gh.png',
      answer: 'Ghana',
      explanation: 'National flag of Ghana.',
    },
    {
      id: 'mam-flag-mauritius',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/mu.png',
      answer: 'Mauritius',
      explanation: 'National flag of Mauritius.',
    },
    {
      id: 'mam-flag-tunisia',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/tn.png',
      answer: 'Tunisia',
      explanation: 'National flag of Tunisia.',
    },
    {
      id: 'mam-flag-namibia',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/na.png',
      answer: 'Namibia',
      explanation: 'National flag of Namibia.',
    },
    {
      id: 'mam-flag-senegal',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/sn.png',
      answer: 'Senegal',
      explanation: 'National flag of Senegal.',
    },
    {
      id: 'mam-flag-zimbabwe',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/zw.png',
      answer: 'Zimbabwe',
      explanation: 'National flag of Zimbabwe.',
    },
    {
      id: 'mam-flag-togo',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/tg.png',
      answer: 'Togo',
      explanation: 'National flag of Togo.',
    },
    {
      id: 'mam-flag-ethiopia',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/et.png',
      answer: 'Ethiopia',
      explanation: 'National flag of Ethiopia.',
    },
    {
      id: 'mam-flag-eritrea',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/er.png',
      answer: 'Eritrea',
      explanation: 'National flag of Eritrea.',
    },
    {
      id: 'mam-flag-sa',
      promptType: 'image',
      promptText: 'Which country does this flag belong to?',
      mediaUrl: 'https://flagcdn.com/w640/za.png',
      answer: 'South Africa',
      explanation: 'National flag of South Africa.',
    },

    {
      id: 'mam-outline-gambia',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/gm/512.png',
      answer: 'Gambia',
      explanation: 'The outline shows Gambia.',
    },
    {
      id: 'mam-outline-egypt',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/eg/512.png',
      answer: 'Egypt',
      explanation: 'The outline shows Egypt.',
    },
    {
      id: 'mam-outline-morocco',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/ma/512.png',
      answer: 'Morocco',
      explanation: 'The outline shows Morocco.',
    },
    {
      id: 'mam-outline-ghana',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/gh/512.png',
      answer: 'Ghana',
      explanation: 'The outline shows Ghana.',
    },
    {
      id: 'mam-outline-mauritius',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/mu/512.png',
      answer: 'Mauritius',
      explanation: 'The outline shows Mauritius.',
    },
    {
      id: 'mam-outline-tunisia',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/tn/512.png',
      answer: 'Tunisia',
      explanation: 'The outline shows Tunisia.',
    },
    {
      id: 'mam-outline-namibia',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/na/512.png',
      answer: 'Namibia',
      explanation: 'The outline shows Namibia.',
    },
    {
      id: 'mam-outline-senegal',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/sn/512.png',
      answer: 'Senegal',
      explanation: 'The outline shows Senegal.',
    },
    {
      id: 'mam-outline-zimbabwe',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/zw/512.png',
      answer: 'Zimbabwe',
      explanation: 'The outline shows Zimbabwe.',
    },
    {
      id: 'mam-outline-togo',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/tg/512.png',
      answer: 'Togo',
      explanation: 'The outline shows Togo.',
    },
    {
      id: 'mam-outline-sierraleone',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/sl/512.png',
      answer: 'Sierra Leone',
      explanation: 'The outline shows Sierra Leone.',
    },
    {
      id: 'mam-outline-eritrea',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/er/512.png',
      answer: 'Eritrea',
      explanation: 'The outline shows Eritrea.',
    },
    {
      id: 'mam-outline-ethiopia',
      promptType: 'image',
      promptText: 'Which African country has this outline?',
      mediaUrl: 'https://cdn.jsdelivr.net/gh/djaiss/mapsicon@master/africa/et/512.png',
      answer: 'Ethiopia',
      explanation: 'The outline shows Ethiopia.',
    },

    {
      id: 'mam-indep-gambia',
      promptType: 'text',
      promptText: 'Which country gained independence on February 18, 1965?\nA) Gambia\nB) Ghana\nC) Senegal\nD) Ethiopia',
      answer: 'Gambia',
      explanation: 'The Gambia gained independence from the United Kingdom on February 18, 1965.',
    },
    {
      id: 'mam-indep-morocco',
      promptType: 'text',
      promptText: 'Which country gained independence on March 2, 1956?\nA) Morocco\nB) Tunisia\nC) Egypt\nD) Ethiopia',
      answer: 'Morocco',
      explanation: 'Morocco gained independence from France on March 2, 1956.',
    },
    {
      id: 'mam-indep-tunisia',
      promptType: 'text',
      promptText: 'Which country gained independence on March 20, 1956?\nA) Tunisia\nB) Morocco\nC) Senegal\nD) Ethiopia',
      answer: 'Tunisia',
      explanation: 'Tunisia gained independence from France on March 20, 1956.',
    },
    {
      id: 'mam-indep-ghana',
      promptType: 'text',
      promptText: 'Which country gained independence on March 6, 1957?\nA) Ghana\nB) Gambia\nC) Senegal\nD) Ethiopia',
      answer: 'Ghana',
      explanation: 'Ghana became the first sub-Saharan African country to gain independence on March 6, 1957.',
    },
    {
      id: 'mam-indep-egypt',
      promptType: 'text',
      promptText: 'Which country gained independence on June 18, 1953?\nA) Egypt\nB) Morocco\nC) Tunisia\nD) Ethiopia',
      answer: 'Egypt',
      explanation: 'Egypt gained independence from the United Kingdom on June 18, 1953.',
    },
    {
      id: 'mam-indep-senegal',
      promptType: 'text',
      promptText: 'Which country gained independence on April 4, 1960?\nA) Senegal\nB) Gambia\nC) Togo\nD) Ethiopia',
      answer: 'Senegal',
      explanation: 'Senegal gained independence from France on April 4, 1960.',
    },
    {
      id: 'mam-indep-togo',
      promptType: 'text',
      promptText: 'Which country gained independence on April 27, 1960?\nA) Togo\nB) Senegal\nC) Sierra Leone\nD) Ethiopia',
      answer: 'Togo',
      explanation: 'Togo gained independence from France on April 27, 1960.',
    },
    {
      id: 'mam-indep-sierraleone',
      promptType: 'text',
      promptText: 'Which country gained independence on April 27, 1961?\nA) Sierra Leone\nB) Togo\nC) Gambia\nD) Ethiopia',
      answer: 'Sierra Leone',
      explanation: 'Sierra Leone gained independence from the United Kingdom on April 27, 1961.',
    },
    {
      id: 'mam-indep-mauritius',
      promptType: 'text',
      promptText: 'Which country gained independence on March 12, 1968?\nA) Mauritius\nB) Namibia\nC) Eritrea\nD) Ethiopia',
      answer: 'Mauritius',
      explanation: 'Mauritius gained independence from the United Kingdom on March 12, 1968.',
    },
    {
      id: 'mam-indep-zimbabwe',
      promptType: 'text',
      promptText: 'Which country gained independence on April 18, 1980?\nA) Zimbabwe\nB) Namibia\nC) Eritrea\nD) Ethiopia',
      answer: 'Zimbabwe',
      explanation: 'Zimbabwe gained independence from the United Kingdom on April 18, 1980.',
    },
    {
      id: 'mam-indep-eritrea',
      promptType: 'text',
      promptText: 'Which country gained independence on May 24, 1993?\nA) Eritrea\nB) Zimbabwe\nC) Namibia\nD) Ethiopia',
      answer: 'Eritrea',
      explanation: 'Eritrea gained independence from Ethiopia on May 24, 1993.',
    },
    {
      id: 'mam-indep-namibia',
      promptType: 'text',
      promptText: 'Which country gained independence on March 21, 1990?\nA) Namibia\nB) Zimbabwe\nC) Eritrea\nD) Ethiopia',
      answer: 'Namibia',
      explanation: 'Namibia gained independence from South Africa on March 21, 1990.',
    },
    {
      id: 'mam-indep-sa',
      promptType: 'text',
      promptText: 'Which country gained independence on May 31, 1910?\nA) South Africa\nB) Namibia\nC) Zimbabwe\nD) Ethiopia',
      answer: 'South Africa',
      explanation: 'The Union of South Africa gained independence from the United Kingdom on May 31, 1910.',
    },

  ],
}
