export default {
  id: 'name-the-country',
  name: 'Name the Country',
  type: 'custom-buzz',
  intro: 'The host describes a country\'s neighbours. Buzz with the country name.',
  rules: [
    'The host reads which countries share a border with a mystery country',
    'Buzz in with the name of the mystery country',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: [
    { label: 'Correct answer', points: 3, phase: 'normal' },
    { label: 'Wrong answer', points: -1, phase: 'normal' },
    { label: 'Correct steal', points: 2, phase: 'steal' },
    { label: 'Wrong steal', points: 0, phase: 'steal' },
  ],
  questions: [
    {
      id: 'ntc-01',
      promptType: 'text',
      promptText: 'I am entirely surrounded by South Africa on all sides. Which country am I?',
      answer: 'Lesotho',
      explanation: 'Lesotho is an enclave state completely surrounded by South Africa — one of only three countries in the world that are entirely within another country.',
    },
    {
      id: 'ntc-02',
      promptType: 'text',
      promptText: 'My only neighbours are Sudan, Ethiopia, and Djibouti. Which country am I?',
      answer: 'Eritrea',
      explanation: 'Eritrea gained independence from Ethiopia in 1993 after a 30-year war. It borders the Red Sea to the east.',
    },
    {
      id: 'ntc-03',
      promptType: 'text',
      promptText: 'I border only Eritrea, Ethiopia, and Somalia. Which country am I?',
      answer: 'Djibouti',
      explanation: 'Djibouti is one of Africa\'s smallest countries and hosts the largest US military base on the continent.',
    },
    {
      id: 'ntc-04',
      promptType: 'text',
      promptText: 'I border Uganda, Tanzania, Burundi, and the Democratic Republic of Congo. Which country am I?',
      answer: 'Rwanda',
      explanation: 'Rwanda is one of Africa\'s most densely populated and smallest countries. It borders Lake Kivu to the west.',
    },
    {
      id: 'ntc-05',
      promptType: 'text',
      promptText: 'I border Algeria, Libya, Chad, Nigeria, Benin, Burkina Faso, and Mali. Which country am I?',
      answer: 'Niger',
      explanation: 'Niger shares borders with seven countries. Despite its size, it is one of the least developed nations in the world.',
    },
    {
      id: 'ntc-06',
      promptType: 'text',
      promptText: 'I border Zambia, Mozambique, South Africa, and Botswana. Which country am I?',
      answer: 'Zimbabwe',
      explanation: 'Zimbabwe is landlocked in Southern Africa. Victoria Falls, one of the Seven Natural Wonders of the World, sits on its border with Zambia.',
    },
    {
      id: 'ntc-07',
      promptType: 'text',
      promptText: 'I border Tunisia, Algeria, Niger, Chad, Sudan, and Egypt. Which country am I?',
      answer: 'Libya',
      explanation: 'Libya is North Africa\'s largest country by area. It borders the Mediterranean Sea to the north.',
    },
    {
      id: 'ntc-08',
      promptType: 'text',
      promptText: 'I border Eritrea, Djibouti, Somalia, Kenya, South Sudan, and Sudan. Which country am I?',
      answer: 'Ethiopia',
      explanation: 'Ethiopia is Africa\'s second most populous country and the only African nation never colonised by a European power (with the exception of a brief Italian occupation).',
    },
    {
      id: 'ntc-09',
      promptType: 'text',
      promptText: 'I border Kenya, Uganda, Rwanda, Burundi, the DRC, Zambia, Malawi, and Mozambique. Which country am I?',
      answer: 'Tanzania',
      explanation: 'Tanzania borders more countries than any other nation in East Africa. It is home to Mount Kilimanjaro and the Serengeti.',
    },
    {
      id: 'ntc-10',
      promptType: 'text',
      promptText: 'I border the DRC, Tanzania, Malawi, Mozambique, Zimbabwe, Botswana, Namibia, and Angola — eight countries in total. Which country am I?',
      answer: 'Zambia',
      explanation: 'Zambia is one of the most landlocked countries in the world, surrounded by eight neighbours. It was formerly known as Northern Rhodesia.',
    },
    {
      id: 'ntc-11',
      promptType: 'text',
      promptText: 'I am surrounded by South Africa, Namibia, and Zimbabwe, with a tiny point where I touch Zambia. Which country am I?',
      answer: 'Botswana',
      explanation: 'Botswana is dominated by the Kalahari Desert. It is home to the Okavango Delta, the world\'s largest inland river delta.',
    },
    {
      id: 'ntc-12',
      promptType: 'text',
      promptText: 'I border Nigeria, Chad, the Central African Republic, Equatorial Guinea, Gabon, and the Republic of Congo. Which country am I?',
      answer: 'Cameroon',
      explanation: 'Cameroon is often called "Africa in miniature" because it contains virtually every climate and geographic feature found across the continent.',
    },
    {
      id: 'ntc-13',
      promptType: 'text',
      promptText: 'I border Chad, Sudan, South Sudan, the DRC, the Republic of Congo, and Cameroon. I have no coastline. Which country am I?',
      answer: 'Central African Republic',
      explanation: 'The Central African Republic is one of the most landlocked and least developed countries in Africa, surrounded entirely by other African nations.',
    },
    {
      id: 'ntc-14',
      promptType: 'text',
      promptText: 'I border Morocco, Western Sahara, Mali, Niger, Libya, and Tunisia. Which country am I?',
      answer: 'Algeria',
      explanation: 'Algeria is Africa\'s largest country by area. Over 80% of its territory is covered by the Sahara Desert. It also shares a short border with Western Sahara (a disputed territory).',
    },
    {
      id: 'ntc-15',
      promptType: 'text',
      promptText: 'I border South Sudan, Kenya, Tanzania, Rwanda, and the Democratic Republic of Congo. Which country am I?',
      answer: 'Uganda',
      explanation: 'Uganda is landlocked in East Africa. Lake Victoria, the largest lake in Africa, lies partly within its borders.',
    },
  ],
}
