export default {
  id: 'nollywood-actors',
  name: 'Nollywood Stars',
  type: 'custom-buzz',
  intro: 'A photo of a famous Nollywood star appears on screen — buzz in and name them!',
  rules: [
    'A photo of a famous Nollywood actor or actress is shown on screen',
    'Buzz in as soon as you know who it is',
    'Correct answer: +3',
    'Wrong answer: -1',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: {
    correctPoints: 3,
    wrongPoints: -1,
    stealEnabled: true,
    correctStealPoints: 2,
    wrongStealPoints: 0,
  },
  questions: [
    {
      id: 'nollywood-01',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Genevieve_Nnaji_in_Weekend_Getaway.png',
      promptText: 'Name this Nollywood star.',
      answer: 'Genevieve Nnaji',
      explanation: 'Genevieve Nnaji directed and starred in "Lionheart" (2018), the first Nigerian original film on Netflix and Nigeria\'s submission for the Academy Award for Best International Feature Film.',
    },
    {
      id: 'nollywood-02',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Omotola_Jalade_Ekeinde_WEF_2015.png',
      promptText: 'Name this Nollywood star.',
      answer: 'Omotola Jalade-Ekeinde',
      explanation: 'Omotola Jalade-Ekeinde — nicknamed "Omosexy" — was named one of Time magazine\'s 100 Most Influential People in the World in 2013, one of only three African artists to make the list.',
    },
    {
      id: 'nollywood-03',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/59/Pete-edochie.jpg',
      promptText: 'Name this Nollywood star.',
      answer: 'Pete Edochie',
      explanation: 'Pete Edochie is widely regarded as the greatest Nollywood actor of his generation. He immortalised Okonkwo in the landmark 1987 NTA/BBC adaptation of Chinua Achebe\'s "Things Fall Apart."',
    },
    {
      id: 'nollywood-04',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Richard_Mofe-Damijo.png',
      promptText: 'Name this Nollywood star.',
      answer: 'Richard Mofe-Damijo',
      explanation: 'Known as RMD, Richard Mofe-Damijo won the Africa Movie Academy Award for Best Actor in 2005 and later served as Delta State Commissioner for Culture and Tourism.',
    },
    {
      id: 'nollywood-05',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Actor_in_Gbomo_Gbomo_Express.png',
      promptText: 'Name this Nollywood star.',
      answer: 'Ramsey Nouah',
      explanation: 'Once called the "Lover Boy of Nollywood," Ramsey Nouah directed and starred in "Living in Bondage: Breaking Free" (2019), the sequel to the 1992 film that launched modern Nollywood.',
    },
    {
      id: 'nollywood-06',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Nkemowoh.jpg',
      promptText: 'Name this Nollywood star.',
      answer: 'Nkem Owoh',
      explanation: 'Nkem Owoh — better known as "Osuofia" — starred in the hugely popular "Osuofia in London" comedy films and is one of Nollywood\'s most beloved comedic actors.',
    },
    {
      id: 'nollywood-07',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Funke_Akindele_at_AMVCA_2020.jpg',
      promptText: 'Name this Nollywood star.',
      answer: 'Funke Akindele',
      explanation: 'Funke Akindele created the hugely popular "Jenifa\'s Diary" franchise and became the first female director to win Best Nigerian Movie at the Africa Movie Academy Awards.',
    },
    {
      id: 'nollywood-08',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Jim_Iyke.jpg',
      promptText: 'Name this Nollywood star.',
      answer: 'Jim Iyke',
      explanation: 'Jim Iyke built his brand as the "Bad Boy of Nollywood" in the 2000s, known for playing rebellious and villainous characters across hundreds of films.',
    },
    {
      id: 'nollywood-09',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Ini-Edo-1.jpg',
      promptText: 'Name this Nollywood star.',
      answer: 'Ini Edo',
      explanation: 'Ini Edo appeared in over 100 Nollywood films within five years of her 2002 debut and was appointed a UNICEF Goodwill Ambassador for Nigeria in 2009.',
    },
    {
      id: 'nollywood-10',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/db/Kate_Henshaw_at_Lawrence_Onochie_50th_birthday09_04_40_659000.jpeg',
      promptText: 'Name this Nollywood star.',
      answer: 'Kate Henshaw',
      explanation: 'Kate Henshaw won the Africa Movie Academy Award for Best Actress in its inaugural year (2005) and is also well known as a prominent fitness and wellness advocate in Nigeria.',
    },
    {
      id: 'nollywood-11',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Mercy_Johnson.png',
      promptText: 'Name this Nollywood star.',
      answer: 'Mercy Johnson',
      explanation: 'Mercy Johnson was one of the highest-paid Nollywood actresses of the 2010s. Her intense emotional performances earned her the fan nickname "Queen of Tears."',
    },
    {
      id: 'nollywood-12',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Regina_Daniels_close.png',
      promptText: 'Name this Nollywood star.',
      answer: 'Regina Daniels',
      explanation: 'Regina Daniels began acting as a child and became a household name across West Africa. She is one of Nollywood\'s most recognised young actresses, known for roles in "The CEO" and "Dumebi the Dictator."',
    },
    {
      id: 'nollywood-13',
      promptType: 'image',
      mediaUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e2/PatienceOzokwor.jpg',
      promptText: 'Name this Nollywood star.',
      answer: 'Patience Ozokwo',
      acceptedAnswers: ['Patience Ozorkwor', 'Mama G'],
      explanation: 'Patience Ozokwo — affectionately known as "Mama G" — is one of Nollywood\'s most iconic veteran actresses, celebrated for her villainous mother roles and winner of multiple Africa Movie Academy Awards.',
    },
  ],
}
