export default {
  label: 'Round 3',
  name: 'Slang Bee',
  type: 'slang',
  intro: 'The host reads a slang term, an example sentence, and its country of origin. Guess the meaning and use it in a sentence.',
  rules: [
    'Buzz in to answer — like a spelling bee, but for slang',
    'Give the meaning of the term to score points',
    'Bonus point if your answer is especially funny',
    'Each team may ask one clarifying question before answering',
    'Allowed: "positive or negative?", "person, action, or situation?", "casual or formal?"',
    'Not allowed: "What language is it?", "What\'s the translation?", "Use it in a sentence for us"',
    'If you miss, one steal is allowed',
  ],
  scoring: [
    { label: 'Correct meaning', points: 2 },
    { label: 'Funny bonus',     points: 1 },
  ],
  questions: [
    {
      id: 'r2q1',
      term: 'Apa',
      language: 'Yoruba',
      country: 'Nigeria',
      sentence: "Don't mind him, he's just being an apa.",
      meaning: 'An unwise person',
    },
    {
      id: 'r2q2',
      term: 'Chini ya maji',
      language: 'Swahili Slang',
      country: 'East Africa',
      sentence: "Labda wanaskia wivu chini ya maji — Maybe they're jealous chini ya maji.",
      meaning: 'Lowkey / Secretively (literally: under the water)',
    },
    {
      id: 'r2q3',
      term: 'Japa japa',
      language: 'Nigerian Slang',
      country: 'Nigeria',
      sentence: 'The way this economy is looking, everybody must japa o.',
      meaning: 'To run away / flee',
    },
    {
      id: 'r2q4',
      term: 'Tu fiakwa gi',
      language: 'Igbo',
      country: 'Nigeria',
      sentence: 'Me, fail this exam again? Tu fiakwa gi!',
      meaning: 'God forbid! / Not my portion',
    },
    {
      id: 'r2q5',
      term: 'Ŋu tikɔ nam',
      language: 'Ewe',
      country: 'Ghana / Togo',
      sentence: 'This gbevu has been making noise all day — ŋu tikɔ nam.',
      meaning: 'I am tired of this / this is annoying',
    },
    {
      id: 'r2q6',
      term: 'Gbevu',
      language: 'Ewe',
      country: 'Ghana / Togo',
      sentence: 'This gbevu has been making noise all day — ŋu tikɔ nam.',
      meaning: 'Young boy causing trouble',
    },
    {
      id: 'r2q7',
      term: '1+1',
      language: 'Ewe Slang',
      country: 'Ghana / Togo',
      sentence: 'He pulled out his 1+1 like it was still 2005.',
      meaning: 'Very old mobile phones (before smartphones)',
    },
    {
      id: 'r2q8',
      term: 'Foutaise',
      language: 'Nouchi',
      country: "Côte d'Ivoire",
      sentence: "Everything he said was foutaise — c'est dohi.",
      meaning: 'Rubbish / nonsense',
    },
    {
      id: 'r2q9',
      term: "C'est dohi",
      language: 'Nouchi',
      country: "Côte d'Ivoire",
      sentence: "Everything he said was foutaise — c'est dohi.",
      meaning: "It's fake / a lie",
    },
    {
      id: 'r2q10',
      term: 'Babie',
      language: 'Nouchi',
      country: "Côte d'Ivoire",
      sentence: "Je vais te babie — I'm going to hit you. / Elle est babie — she is pretty.",
      meaning: 'To hit someone; also means someone is attractive',
    },
    {
      id: 'r2q11',
      term: 'Gemeh',
      language: 'Cameroon Slang',
      country: 'Cameroon',
      sentence: "Don't mind him — gemeh, gemeh, always making noise and doing nothing.",
      meaning: 'Someone who talks too much but does nothing',
    },
    {
      id: 'r2q12',
      term: "C'est le lait?",
      language: 'Cameroon Slang',
      country: 'Cameroon',
      sentence: "He walked in with a new car like c'est le lait.",
      meaning: "What were you thinking? / Showing off in a self-congratulatory way",
    },
    {
      id: 'r2q13',
      term: 'Ko Jean Claude Vandamme',
      language: 'Congolese Slang',
      country: 'DRC',
      sentence: 'We got to the party late, so I just found one corner and Jean Claude Vandamme there.',
      meaning: 'To sit down (Nazali Jean Claude Vandamme = I am sitting down)',
    },
  ],
}
