export default {
  label: 'Round 3',
  name: 'Slang Bee',
  type: 'slang',
  intro: 'The host reads a slang term, an example sentence, and its country of origin. Try and guess the meaning of the word!',
  rules: [
    'Host reads the term, example sentence, and country of origin',
    'Buzz in to give the meaning — correct answer: +3 pts',
    'Wrong answer: −1 pt',
    'Bonus +1 if your answer is especially funny (host decides)',
    'One steal allowed after a miss — +2 correct, no penalty for wrong steal',
  ],
  scoring: [
    { label: 'Correct meaning', points: 3 },
    { label: 'Funny bonus',     points: 1 },
    { label: 'Wrong answer',  points: -1 },
    { label: 'Correct steal',   points: 2 },
    { label: 'Wrong steal',     points: 0 },
  ],
  questions: [
    {
      id: 'r2q1',
      term: 'Yawa',
      language: 'Ghanaian Slang',
      country: 'Ghana',
      sentence: 'I forgot my wallet at dinner — serious yawa o.',
      meaning: 'Embarrassment, trouble, or a messy situation',
    },
    {
      id: 'r2q2',
      term: 'Ndem',
      language: 'Camfranglais',
      country: 'Cameroon',
      sentence: "If I ndem this exam after all that studying, I'll cry.",
      meaning: 'To fail',
    },
    {
      id: 'r2q3',
      term: 'Ngori',
      language: 'Sheng',
      country: 'Kenya',
      sentence: "Don't go there tonight, you will have ngori.",
      meaning: 'Trouble or difficulty',
    },
    {
      id: 'r2q4',
      term: 'Tchalé',
      language: 'Ewe Slang',
      country: 'Togo',
      sentence: "Tchalé, you good?",
      meaning: 'Friend, buddy, guy',
    },
    {
      id: 'r2q5',
      term: 'Wolokoso',
      language: 'Ugandan Slang',
      country: 'Uganda',
      sentence: 'That group chat is just wolokoso from morning till night.',
      meaning: 'Gossip, rumors, or reckless chatter',
    },
    {
      id: 'r2q6',
      term: 'Salt Sana',
      language: 'Zambian Slang',
      country: 'Zambia',
      sentence: 'Michael: "The food here is overpriced and overrated", John: "Yeah, salt sana!"',
      meaning: 'Total agreement, "exactly" — said when someone makes a point you fully agree with',
    },
    {
      id: 'r2q7',
      term: 'Poa',
      language: 'Swahili Slang',
      country: 'Tanzania',
      sentence: 'Jonas: "You good?", Abimbola: "Poa."',
      meaning: 'Cool, fine, no worries',
    },
    {
      id: 'r2q9',
      term: 'Doff',
      language: 'Wolof',
      country: 'Senegal',
      sentence: 'What happened to you? You look like a doff o',
      meaning: 'A crazy person',
    },
    {
      id: 'r2q10',
      term: 'JJC',
      language: 'Nigerian Slang',
      country: 'Nigeria',
      sentence: 'Don\'t send him to go and price anything at the market, he will pay full price like a JJC.',
      meaning: 'A novice or newcomer who doesn\'t know how things work (short for Johnny Just Come)',
    },
    {
      id: 'r2q11',
      term: 'Sapa',
      language: 'Nigerian Slang',
      country: 'Nigeria',
      sentence: 'This sapa is hitting different this month — I can\'t even buy data.',
      meaning: 'The state of being broke — Serious Absence of Purchasing Ability',
    },
     {
      id: 'r2q12',
      term: 'Ni Kunoma',
      language: 'Sheng',
      country: 'Kenya',
      sentence: "Stay away from that street, ni kunoma.",
      meaning: "It's a problem / not safe",
    },
    {
      id: 'r2q13',
      term: 'Miswa iwe',
      language: 'Shona Slang',
      country: 'Zimbabwe',
      sentence: 'You want to fight over a parking spot at the braai? Miswa iwe.',
      meaning: 'Relax / bro chill',
    },
    {
      id: 'r2q14',
      term: 'Chap chap',
      language: 'Francophone West African Slang',
      country: 'Francophone West Africa',
      sentence: 'Man, we have no time — finish this chap chap.',
      meaning: 'Quickly / hurry up',
    },
    {
      id: 'r2q15',
      term: 'Sciencer',
      language: 'Nouchi (Ivorian Slang)',
      country: 'Côte d\'Ivoire',
      sentence: 'If two of your friends are fighting, you can come to them and tell them that they should sciencer.',
      meaning: 'To think through a situation / show empathy and help someone reason it out',
    },
    {
      id: 'r2q16',
      term: 'C\'est dohi',
      language: 'Nouchi (Ivorian Slang)',
      country: 'Côte d\'Ivoire',
      sentence: 'Whoever told you this — c\'est dohi.',
      meaning: 'It\'s fake / it\'s wrong',
    },
    {
      id: 'r2q17',
      term: 'Sorti dans dos',
      language: 'Nouchi (Ivorian Slang)',
      country: 'Côte d\'Ivoire',
      sentence: 'They didn\'t believe in me, but I sorti dans dos.',
      meaning: 'Made it despite all the odds',
    },
    {
      id: 'r2q18',
      term: 'Goumin',
      language: 'Nouchi (Ivorian Slang)',
      country: 'Côte d\'Ivoire',
      sentence: 'He broke up with her? Yes, he put her in a big goumin.',
      meaning: 'The heartbroken mental state after a painful loss or betrayal',
    },
    {
      id: 'r2q19',
      term: 'Moti',
      language: 'Sheng',
      country: 'Kenya',
      sentence: 'She took the moti to the restaurant.',
      meaning: 'Car',
    },
    {
      id: 'r2q20',
      term: 'Ingiza njeve',
      language: 'Sheng',
      country: 'Kenya',
      sentence: 'When the police came, wali-ingiza njeve.',
      meaning: 'To become scared / panic',
    },
    {
      id: 'r2q21',
      term: 'Amebo',
      language: 'Nigerian Slang',
      country: 'Nigeria',
      sentence: 'That girl is an amebo.',
      meaning: 'A gossip / someone who talks too much about other people’s business',
    },
    {
      id: 'r2q22',
      term: 'Cho cho cho',
      language: 'Nigerian Slang',
      country: 'Nigeria',
      sentence: 'All this cho cho cho in the group chat is too much.',
      meaning: 'Endless chatter / noisy gossip',
    },
    {
      id: 'r2q23',
      term: 'Palava',
      language: 'Nigerian Slang',
      country: 'Nigeria',
      sentence: 'What a palava! It took three hours to check in.',
      meaning: 'Stressful trouble / unnecessary wahala',
    },
    {
      id: 'r2q24',
      term: 'I.J.B.G',
      language: 'Nigerian Slang',
      country: 'Nigeria',
      sentence: 'He came back speaking with an accent after six months — full IJBG.',
      meaning: 'I Just Got Back (used for someone who just returned from abroad)',
    },
    {
      id: 'r2q25',
      term: 'Idan',
      language: 'Nigerian Slang',
      country: 'Nigeria',
      sentence: 'Idan doesn’t take notes in class, but gets A’s.',
      meaning: 'A boss / someone highly skilled or exceptional',
    },
    {
      id: 'r2q26',
      term: 'Efiko',
      language: 'Yoruba / Nigerian Slang',
      country: 'Nigeria',
      sentence: 'The whole class was copying from her. She’s the efiko of the group.',
      meaning: 'A nerd / very brilliant person',
    },
    {
      id: 'r2q27',
      term: 'Foutaise',
      language: 'Francophone West African Slang',
      country: 'Francophone West Africa',
      sentence: 'They think they can do me like that? They are full of foutaise o.',
      meaning: 'Rubbish / nonsense',
    },
    {
      id: 'r2q28',
      term: 'Kpakpato',
      language: 'Nouchi (Ivorian Slang)',
      country: 'Côte d\'Ivoire',
      sentence: 'Too much kpakpato in your business here.',
      meaning: 'Someone who talks too much / gossip',
    },
    {
      id: 'r2q29',
      term: 'Eleyi',
      language: 'Togolese Slang',
      country: 'Togo',
      sentence: 'How is work? Eleyi.',
      meaning: 'It’s all good / going well',
    },
    {
      id: 'r2q30',
      term: 'Kouma',
      language: 'Nouchi / Francophone Slang',
      country: 'Mali, Côte d\'Ivoire',
      sentence: 'Those people kouma too much.',
      meaning: 'To talk, usually behind someone’s back',
    },
    {
      id: 'r2q31',
      term: 'Doser',
      language: 'Francophone West African Slang',
      country: 'Francophone West Africa',
      sentence: 'Eh brother, dose.',
      meaning: 'Calm down / take it easy',
    },
    {
      id: 'r2q32',
      term: 'Ya',
      language: 'Camfranglais',
      country: 'Cameroon',
      sentence: 'Do you ya what I’m saying?',
      meaning: 'Understand',
    },
  ],
}
