export default {
  label: 'Round 3',
  name: 'Slang Bee',
  type: 'slang',
  intro: 'The host reads a slang term, an example sentence, and its country of origin. Try and guess the meaning of the word!',
  rules: [
    'Host reads the term, example sentence, and country of origin',
    'Buzz in to give the meaning — correct answer: +3 pts',
    'Bonus +1 if your answer is especially funny (host decides)',
    'One steal allowed after a miss — +2 correct, −1 wrong',
  ],
  scoring: [
    { label: 'Correct meaning', points: 3 },
    { label: 'Funny bonus',     points: 1 },
    { label: 'Correct steal',   points: 2 },
    { label: 'Wrong steal',     points: -1 },
  ],
  questions: [
    {
      id: 'r2q1',
      term: 'Yawa',
      language: 'Ghanaian Slang',
      country: 'Ghana',
      sentence: 'I forgot my wallet at dinner — serious yawa o.',
      meaning: 'Embarrassment, trouble, or a messy situation',
    },
    {
      id: 'r2q2',
      term: 'Ndem',
      language: 'Camfranglais',
      country: 'Cameroon',
      sentence: "If I ndem this exam after all that studying, I'll cry.",
      meaning: 'To fail',
    },
    {
      id: 'r2q3',
      term: 'Ngori',
      language: 'Sheng',
      country: 'Kenya',
      sentence: "Don't go there tonight, kuna ngori.",
      meaning: 'Trouble or difficulty',
    },
    {
      id: 'r2q4',
      term: 'Tchalé',
      language: 'Ewe Slang',
      country: 'Togo',
      sentence: "Tchalé, you good?",
      meaning: 'Friend, buddy, guy',
    },
    {
      id: 'r2q5',
      term: 'Wolokoso',
      language: 'Ugandan Slang',
      country: 'Uganda',
      sentence: 'That group chat is just wolokoso from morning till night.',
      meaning: 'Gossip, rumors, or reckless chatter',
    },
    {
      id: 'r2q6',
      term: 'Chalo',
      language: 'Zambian Slang',
      country: 'Zambia',
      sentence: 'The music festival last night was amazing. Zambia ku chalo!',
      meaning: 'To the world',
    },
    {
      id: 'r2q7',
      term: 'Salt Sana',
      language: 'Zambian Slang',
      country: 'Zambia',
      sentence: 'Michael: "The food here is overpriced and overrated", John: "Yeah, salt sana!"',
      meaning: 'Total agreement, "exactly" — said when someone makes a point you fully agree with',
    },
    {
      id: 'r2q8',
      term: 'Poa',
      language: 'Swahili Slang',
      country: 'Tanzania',
      sentence: '"You good?" "Poa."',
      meaning: 'Cool, fine, no worries',
    },
    {
      id: 'r2q9',
      term: 'Doff',
      language: 'Wolof',
      country: 'Senegal',
      sentence: 'Who designed this? Doff?',
      meaning: 'A crazy person',
    },
  ],
}
