export default {
  id: 'who-am-i',
  name: 'Who Am I?',
  type: 'custom-buzz',
  intro: 'Three clues about a notable African figure — buzz in as soon as you know who it is. Earlier buzzes score more.',
  rules: [
    'The host reads three clues one at a time about a notable African figure',
    'Buzz in as soon as you think you know — you don\'t have to wait for all three clues',
    'Correct answer: +3',
    'Wrong answer: -1 (remaining clues continue)',
    'After a miss, one steal is available (+2 / 0)',
  ],
  scoring: [
    { label: 'Correct answer', points: 3, phase: 'normal' },
    { label: 'Wrong answer', points: -1, phase: 'normal' },
    { label: 'Correct steal', points: 2, phase: 'steal' },
    { label: 'Wrong steal', points: 0, phase: 'steal' },
  ],
  questions: [
    {
      id: 'wai-01',
      promptType: 'text',
      promptText: 'I spent 27 years in prison — first on Robben Island, then Pollsmoor, then Victor Verster.\nI co-founded the ANC Youth League in 1944.\nI became South Africa\'s first democratically elected president in 1994.',
      answer: 'Nelson Mandela',
      explanation: 'Nelson Mandela (1918–2013) was imprisoned from 1964 to 1990 and served as South Africa\'s president from 1994 to 1999.',
    },
    {
      id: 'wai-02',
      promptType: 'text',
      promptText: 'I was born near Johannesburg and was exiled from South Africa for approximately 30 years.\nI was the first African artist to win a Grammy Award, in 1965, for a collaborative album with Harry Belafonte.\nI introduced the world to South African music through songs like "Pata Pata" and was nicknamed "Mama Africa".',
      answer: 'Miriam Makeba',
      explanation: 'Miriam Makeba (1932–2008) was a South African singer and activist whose music helped put African sound on the global stage.',
    },
    {
      id: 'wai-03',
      promptType: 'text',
      promptText: 'I ruled my country for over 40 years and was considered divine by a religious movement originating in Jamaica.\nI was the only African leader to personally address the League of Nations after my country was invaded by Italy.\nI was the last emperor of Ethiopia.',
      answer: 'Haile Selassie',
      explanation: 'Haile Selassie (1892–1975) ruled Ethiopia from 1930 until 1974. He is revered as a messianic figure in Rastafari.',
    },
    {
      id: 'wai-04',
      promptType: 'text',
      promptText: 'I founded the Green Belt Movement, which planted over 47 million trees across Africa.\nI was the first African woman to win the Nobel Peace Prize.\nI was a Kenyan environmental and political activist.',
      answer: 'Wangari Maathai',
      explanation: 'Wangari Maathai (1940–2011) won the Nobel Peace Prize in 2004 for her work connecting environmental conservation with democracy and women\'s rights.',
    },
    {
      id: 'wai-05',
      promptType: 'text',
      promptText: 'My most famous political motto was "Seek ye first the political kingdom."\nI was a leading advocate for Pan-Africanism and a founding member of the Organisation of African Unity.\nI was the first Prime Minister and later first President of Ghana.',
      answer: 'Kwame Nkrumah',
      explanation: 'Kwame Nkrumah (1909–1972) led Ghana to independence in 1957 and became one of the founding fathers of Pan-Africanism.',
    },
    {
      id: 'wai-06',
      promptType: 'text',
      promptText: 'I created a new genre of music by fusing jazz, funk, and Yoruba traditional music.\nI declared my compound in Lagos a sovereign republic called the "Kalakuta Republic."\nI am the Nigerian musician widely credited as the father of Afrobeat.',
      answer: 'Fela Kuti',
      explanation: 'Fela Anikulapo Kuti (1938–1997) was a revolutionary musician, bandleader, and activist whose music challenged military rule in Nigeria.',
    },
    {
      id: 'wai-07',
      promptType: 'text',
      promptText: 'I won the Nobel Peace Prize in 2011, sharing it with two other women.\nI was Africa\'s first elected female head of state.\nI was President of Liberia.',
      answer: 'Ellen Johnson Sirleaf',
      explanation: 'Ellen Johnson Sirleaf (born 1938) served as President of Liberia from 2006 to 2018, becoming the first elected female head of state in Africa.',
    },
    {
      id: 'wai-08',
      promptType: 'text',
      promptText: 'I wrote my debut novel partly in response to colonial depictions of Africa — especially the work of Joseph Conrad.\nMy novel has sold over 20 million copies worldwide and is taught in schools across the globe.\nI am a Nigerian author known as the father of African literature in English, best known for "Things Fall Apart".',
      answer: 'Chinua Achebe',
      explanation: 'Chinua Achebe (1930–2013) transformed African literature with Things Fall Apart (1958), which depicted Igbo society before and during colonial disruption.',
    },
    {
      id: 'wai-09',
      promptType: 'text',
      promptText: 'I served as my country\'s first Prime Minister for only 10 weeks before being overthrown in a coup.\nMy assassination in 1961 was later acknowledged to have had involvement from Western intelligence agencies.\nI was the first Prime Minister of the Democratic Republic of Congo.',
      answer: 'Patrice Lumumba',
      explanation: 'Patrice Lumumba (1925–1961) was a Congolese independence leader and the DRC\'s first Prime Minister, whose assassination became a symbol of Cold War interference in Africa.',
    },
    {
      id: 'wai-10',
      promptType: 'text',
      promptText: 'I was the first Arab writer to win the Nobel Prize in Literature, receiving it in 1988.\nMy Cairo Trilogy chronicles three generations of a middle-class family in 20th-century Egypt.\nI was an Egyptian novelist whose works explored life in the alleyways and coffeehouses of Cairo.',
      answer: 'Naguib Mahfouz',
      explanation: 'Naguib Mahfouz (1911–2006) wrote over 30 novels and 350 short stories. His Cairo Trilogy is considered one of the masterpieces of world literature.',
    },
    {
      id: 'wai-11',
      promptType: 'text',
      promptText: 'I renamed my country from Upper Volta to Burkina Faso, meaning "Land of Upright People."\nI was known as "Africa\'s Che Guevara" for my revolutionary socialist politics.\nI was the President of Burkina Faso from 1983 until my assassination in 1987.',
      answer: 'Thomas Sankara',
      explanation: 'Thomas Sankara (1949–1987) was a revolutionary leader who launched anti-corruption campaigns, promoted women\'s rights, and pursued African self-reliance before being killed in a coup.',
    },
    {
      id: 'wai-12',
      promptType: 'text',
      promptText: 'My TED Talk "We Should All Be Feminists" was sampled by Beyoncé on her 2013 album.\nMy novel "Americanah" explores race and identity through an African woman\'s experience in the United States.\nI am a Nigerian author known for "Half of a Yellow Sun" and "Purple Hibiscus."',
      answer: 'Chimamanda Ngozi Adichie',
      explanation: 'Chimamanda Ngozi Adichie (born 1977) is one of the most celebrated contemporary African writers, known for her novels and essays on feminism, identity, and Nigerian history.',
    },
  ],
}
